### ISSUE TITLE
Provide callback for after_create with attachments

### ISSUE THREAD

**Issue by rfc2822** [thoughtbot/paperclip#1110]
At the moment, it's not possible to use attachments in an after_create callback because the attachments are saved in after_save which is called after after_create.

So if I want to observe creation of a record (for instance, a comment with an attached image) and then, for instance, send an email including the attachment to subscribers, I use this workaround at the moment:

```ruby
class CommentObserver < ActiveRecord::Observer
  def after_create(comment)
    # queue notification because attachment is not stored yet
    comment.instance_variable_set '@notify_subscribers', 1
  end

  def after_save(comment)
    if comment.instance_variable_get('@notify_subscribers')
      # ... send notifications, attachment is stored now
    end
  end
end
```

However, I'd like to use a single callback without dirty workarounds. So I suggest to add some callbacks to Paperclip that make this possible. I haven't thought about a useful strategy and callback names yet, but it should include something like `after_create_with_attachments` that should be called on the same conditions as after_create, but with attachments already stored.

**Comment by maclover7** [comment]
Hi @rfc2822 ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
Given there's no further activity around this issue any more, and @djcp code works for you, I’ll close this issue for now. Happy to continue further discussion if we can find a better solution for this. Thank you all for your input!

**Comment by GBH** [comment]
This is still an issue. Here's my use-case:

- file gets attached to a newly created record
- `after_create` callback schedules a task via delayed_job
- delayed_job opens the file and does things

It works as expected *except* in test environment. In test environment delayed_job just runs method immediately. So `File.open(some_record.file.path)` gonna explode with `Errno::ENOENT: No such file or directory` because paperclip didn't flush file into filesystem with `after_save` yet.

I'd really like to avoid doing `if Rails.env.test?` inside my code
