### ISSUE TITLE
"should validate_attachment_content_type" not working (rspec)

### ISSUE THREAD

**Issue by renevall** [thoughtbot/paperclip#1158]
I'm doing the basic unit tests for the attachment I have for my model, but I keep getting this error 

"Failure/Error: rejecting('text/plain', 'text/xml') }
     NoMethodError:
       **undefined method `any?' for nil:NilClass** "
"

Here is my model 

``` ruby

 #thumbs
  attr_accessible :image
  has_attached_file :image, :styles => { :large => "600x550>", 
    :medium => "300x275>" }

  validates_attachment :image,
  :content_type => { :content_type => ["image/jpeg", "image/png"] },
  :size => { :in => 0..2.megabytes }

```

Here is the spec

``` ruby
describe "paperclip image" do
    it { should have_attached_file(:image) }
    it { should validate_attachment_content_type(:image).
                allowing('image/png', 'image/gif', 'image/jpeg').
                rejecting('text/plain', 'text/xml') }
    it { should validate_attachment_size(:image).
                less_than(2.megabytes) }
  end
```

I'm not missing "subject", actually this is the only test failing.

**Comment by bwest87** [comment]
yeah, I ran into this same error. I fixed it, but it appears this happens whenever anything in the "allowing" method is spelled wrong. In my case, I accidentally spelled it "jpg" rather than "jpeg", and all I got was the "any?" error, which is really not helpful. If you misspell it in the model, you get a "content type is illegal", which is helpful. Anyway, thanks @ResidentBio  for showing this, it led me down the right path.

**Comment by MartinB83** [comment]
I ran into the same issue today and cannot figure out how to fix it.
In my model:

``validates_attachment_content_type :file, :content_type => ["application/pdf"]``

In my spec file:

``it { should validate_attachment_content_type(:file).allowing('application/pdf').rejecting('text/plain', 'text/xml') }``

throws:

undefined method `validate_attachment_content_type' for #<RSpec::ExampleGroups::EventInformation:0x007fd75b1eeee0>
