### ISSUE TITLE
Errno::ENAMETOOLONG: File name too long for images downloaded from long urls using UriAdapter

### ISSUE THREAD

**Issue by skyshard** [thoughtbot/paperclip#1246]
TempfileFactory generates a file with a long name, and then `destination.write` on line 33 in uri_adapter.rb fails:

https://github.com/thoughtbot/paperclip/blob/62264c65f8b327b8078151e2d4cd589c845a1b5a/lib/paperclip/io_adapters/uri_adapter.rb#L33

It seems that the main problem is that anything after the last '/' in the url is taken to be the filename, so long query strings / long urls will fail

**Comment by maclover7** [comment]
Hi @skyshard and @inspire22 ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by codeodor** [comment]
This is not only a problem with `UriAdapter`. I am seeing it intermittently with an image that just has a lot of post-processing going on. In our case, since `Thumbnail` sets `@basename            = File.basename(@file.path, @current_format)` and `@file` is already a `Tempfile` it has a long name. And then I guess it keeps getting longer with each post-process.

Since `Tempfile` is already supposed to be unique from the OS, can Paperclip just set @basename to the original filename? Or maybe a hash of the filename? That should guarantee this error does not show up.

**Comment by maclover7** [comment]
Would you be willing to send in a PR?

**Comment by codeodor** [comment]
Yes. It's on my todo list, hopefully I can get to it this weekend.

**Comment by codeodor** [comment]
I never got around to it this weekend. But I still hope to this week.

**Comment by codeodor** [comment]
PR is on https://github.com/thoughtbot/paperclip/pull/1833.

**Comment by codeodor** [comment]
I think all places in paperclip now use paperclip's Tempfile rather than Ruby's, so this *should* be able to be closed now.

**Comment by tute** [comment]
Thank you @codeodor!
