### ISSUE TITLE
Rails 4 model missing required attr_accessor for 'attachment_file_name'

### ISSUE THREAD

**Issue by adamyonk** [thoughtbot/paperclip#1304]
When I try to upload a file I get:

```
Paperclip::Error in StorySubmissionsController#create
StorySubmission model missing required attr_accessor for 'attachment_file_name'
```

Model:

``` ruby
class StorySubmission < ActiveRecord::Base
  has_attached_file :attachment
  ...
end
```

Controller:

``` ruby
class StorySubmissionsController < ApplicationController
  def create
    @story_submission = StorySubmission.new story_submission_params
  end

  private

  def story_submission_params
    params.require(:story_submission).permit(:name, :email, :story, :attachment)
  end
end
```

Is Paperclip just not compatible with Rails 4 and strong_parameters (without the protected_attributes gem), or what am I missing here?

**Comment by dayanthan** [comment]
working fine.

rails g paperclip [Model Name] [Attachment]

**Comment by cwRichardKim** [comment]
running into this issue now. was anyone able to resolve it? triple checked migrations

**Comment by PapePathe** [comment]
Running the same issue, in rails admin?

**Comment by ryanbelke** [comment]
If you are running into this error its because you don't have the correct columns in your DB for paperclip

You can do a migration as follows:
class AddThumbNailToArticles < ActiveRecord::Migration[5.0]
  def change
    add_attachment :articles, :thumbnail
  end
end

This will add 4 column names to my articles DB that paperclip needs to save info to the DB. Make sure to read the paperclip docs about the migration section

**Comment by shcyiza** [comment]
i had the same issue because of a typo in migration (happens more that i would like to admit) thank got i spotted it early in the project
