### ISSUE TITLE
Making duplicate error messages configurable

### ISSUE THREAD

**Issue by scottsherwood** [thoughtbot/paperclip#1367]
Hi,

After a little investigation into why validation messages are being duplicated, paperclip now sets errors on both the base and attribute. #1253 

I'm suggesting that we make this configurable so that those of us who only want them on base (or the attr) can easily allow this. As suggested ( @djcp  ) I'm opening an issue so that this can be discussed and get everyone's feedback.

So any suggestions on how this could be implemented? What the defaults should be? If its even a good idea to add the config? etc..

**Comment by maclover7** [comment]
Hi @scottsherwood ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, would you be willing to send in a PR to solve the problem? Thanks!

**Comment by scottsherwood** [comment]
Hi @maclover7

Yes this is still an issue with paperclip, but I'm afraid my workload at the minute is a little to high and i'm unlikely to have any time to work on this anytime soon.

Sorry
Scott

**Comment by tute** [comment]
Will close this issue in favor of discussions in the two open PRs. Thank you all.

**Comment by tute** [comment]
Reopening this issue, as the two PRs were not good solutions for the problem. The issue persists, and a suggested workaround in application code is:

```ruby
class Attachment < ActiveRecord::Base
  after_validation :clean_up_paperclip_errors

  private

  # This is because paperclip duplicates error messages
  # See: https://github.com/thoughtbot/paperclip/pull/1554 and
  # https://github.com/thoughtbot/paperclip/commit/2aeb491fa79df886a39c35911603fad053a201c0
  def clean_up_paperclip_errors
    errors.delete(:file)
  end
end
```

**Comment by txapelgorri** [comment]
@tute: thanks for this workaround, works great :)

**Comment by brendon** [comment]
Hi @tute, I think a proper configurable fix should be pursued because the solution you mention here: https://github.com/thoughtbot/paperclip/issues/1367#issuecomment-217934878 fails to take into account the `presence` validation that is only added to `base`, thus this error gets deleted and we end up with a similar problem that form builder users were having with regards to missing or hidden messages.

I think we all agree that this should be something handled internally to Paperclip rather than scattering these callbacks across a bunch of models in an app, especially considering the workaround isn't 100% working.

Perhaps we could decide on what the configuration option looks like, then work from there on a PR?

Something like:?

```ruby
Paperclip.options[:add_validation_errors_to] = :base
Paperclip.options[:add_validation_errors_to] = :attribute
Paperclip.options[:add_validation_errors_to] = :both
```

The presence validation would always be added to base regardless.

What do you think?

**Comment by brendon** [comment]
I've created a PR to fix this. I hope it meets your requirement in #2090:

> As stated in the other PR, I'll consider a fix that, without adding much complexity, takes care of both use cases.

**Comment by mike-burns** [comment]
Thank you for the feature request. Unfortunately we will be deprecating Paperclip and therefore will no longer be accepting new features.
