### ISSUE TITLE
lambda is not support for path with S3

### ISSUE THREAD

**Issue by rahilvirani** [thoughtbot/paperclip#1392]
I'm trying to make a model which keeps all the attachments in one table. This means each model can has_one :attachment, so instead of adding columns each time i need a new attachment i simply create a row in the table. Therefore, i need a dynamic path to load within a Proc so it can be different for each models

 has_attached_file   :image ,
      styles:           lambda { |a|  a.instance.styles            },
      default_url:    lambda {  |a|  a.instance.default_url       },
      default_style: lambda {  |a|  a.instance.default_style     },
      path:             lambda {  |a|  a.instance.path              }

Attachment instance methods looks like this:
  def styles
    params[:styles] ? params[:styles] : self.class.default_styles
  end

Error that occurs when using lambda with S3 in path
NoMethodError: undefined method `gsub' for #<Proc:0x007fb71f754148>
from /Users/dev/.rvm/gems/ruby-2.0.0-p247@influitive/gems/paperclip-3.5.2/lib/paperclip/storage/s3.rb:141:in`block in extended'

**Comment by camhine** [comment]
Sorry for posting on a closed ticket. But I had similar issues over the past few days. Seeing as I sunk some time into it I thought it was worth contributing to the thread.

I'm setting up paperclip to use the local filesystem in dev and S3 in prod. To do this I need to supply different `path` and `url` options to `has_attached_file` on my model.

Looking at the `has_attached_file` [documentation](http://www.rubydoc.info/gems/paperclip/Paperclip/ClassMethods) I thought: I'll dynamically define my interpolation string for `:url` and `:path` in my model by passing a method name as a symbol as a argument.

But when I ran it in our staging environment: `NoMethodError: undefined method `gsub' for :path:Symbol`. 

It seems that `has_attached_file` behaves differently in S3 storage than file system storage.

I'm glad I found this issue because I wasn't aware that I should be using an interpolation for this sort of thing.

If there is any interest I could write a short section on how to use Paperclip with local filesystem in dev and S3 in production for inclusion in the README or anywhere else that would make sense.
