### ISSUE TITLE
Confused over ContentTypeDetector content type detection.

### ISSUE THREAD

**Issue by josephbridgwaterrowe** [thoughtbot/paperclip#1713]
I don't like raising an issue for this, but I'm a little a little confused over the content type detection.

From the `ContentTypeDetector` comments:

``` ruby
#3. Standard types: Return the first standard (without an x- prefix) entry
#    in MIME::Types
```

However by my understanding of the code it looks to me that only cases `1, 2, 5` are supported.

``` ruby
    def detect
      if blank_name?
        SENSIBLE_DEFAULT
      elsif empty_file?
        EMPTY_TYPE
      elsif calculated_type_matches.any?
        calculated_type_matches.first
      else
        type_from_file_command || SENSIBLE_DEFAULT
      end.to_s
    end
```

So I monkey patched the method locally to look like this (quick and dirty with no x- prefix exclusions):

``` ruby
    def detect
      if blank_name?
        SENSIBLE_DEFAULT
      elsif empty_file?
        EMPTY_TYPE
      elsif calculated_type_matches.any?
        calculated_type_matches.first
      elsif possible_types.any?
        possible_types.first
      else
        type_from_file_command || SENSIBLE_DEFAULT
      end.to_s
    end
```

Am I completely off base?

Thanks for your time.

Joe.

**Comment by dougc84** [comment]
+1.  XLSX and DOCX files routinely return "application/zip," which is incorrect.  However, I'm not sure this is `Paperclip`'s `ContentTypeParser`'s concern.  Using the file utility to check the file type of a DOCX or XLSX file also returns "application/zip," which is incorrect.  An alternate workaround, instead of monkey patching, would be as follows.  However, this may lead to some content type spoofing.

```ruby
# The relevant lines of a Documentation class, assuming you want to only upload a
# word document or a PDF.  Obviously, this will need to change based on your
# model's implementation.
# 
# Also assuming the attachment fields are based off the :attachment key (#attachment=,
# #attachment_file_name, #attachment_content_type, etc.)
# 
# app/models/documentation.rb
# 
class Documentation < ActiveRecord::Base
  include Model::EnsureDOCXContentType # more on this in a minute

  has_attached_file :attachment

  # Option 1: Be lenient on the content type and accept "application/zip",
  # but also check the file extension.
  validates_attachment_content_type :attachment, content_type: [
      'application/msword',
      'application/pdf',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/zip']
  # NOTE: You can get valid extensions for each content type by typing, in the console:
  #   MIME::Types['application/msword'].first.extensions #=> ['doc', 'dot', 'wrd']
  validates_attachment_file_name :attachment, matches: [/\.(pdf|(docx?)|dot|wrd)\z/]

  # Option 2: Be strict on the content type.  File extension checking not necessary,
  # but may cause occasional "file type not accepted" errors.
  validates_attachment_content_type :attachment, content_type: [
      'application/msword',
      'application/pdf',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document']
end

# Add a module that you can include on any Model.  You could also do the same in
# the controller if you want; the choice of where it goes is up to your methodology.
# Module naming and placement is up to you, but I prefer to namespace Model concerns
# to the Model namespace, Controller concerns to the Controller namespace, etc.
# 
# The real point of this module is the #set_proper_docx_content_type_for_attachment
# method, which is performed as a before_validation callback.
# 
# app/concerns/model/ensure_docx_content_type.rb
# 
module Model::EnsureDOCXContentType
  module InstanceMethods
    # 
    # If the #attachment is set, and the content type is application/zip, but has
    # a .docx extension, change the #attachment_content_type field.
    # 
    def set_proper_docx_content_type_for_attachment
      return unless attachment?
      return unless attachment_content_type == 'application/zip'
      return unless attachment_file_name =~ /\.docx\z/

      attachment_content_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    end
  end

  def self.included(base)
    base.include InstanceMethods
    # This should be a before_validation callback on the Model, because if Paperclip's
    # validator hits this before this can run, its point is moot.
    base.before_validation :set_proper_docx_content_type_for_attachment
  end
end
```

**Comment by jonathan-upstart** [comment]
Interesting solution, thanks for the suggestion! We might include this module instead of monkey patching.

**Comment by josephbridgwaterrowe** [comment]
I think that either the code needs to be changed to that of my monkey patch (with provisions to exclude x- prefixed types) or item 3 should be removed from the comments, unless my understanding of this comment is wrong. :smile:

**Comment by mgornick** [comment]
@jonathan-upstart +1 to your earlier comment about having a whitelist scenario. This way safe attachments, such as those generated server-side, can be explicitly set without worrying about the monkey patch and future file types.

> An alternative is to provide an option that allows users to explicitly specify content_type whenever an attachment is added. This way we could override the default inferred content_type in specific whitelisted scenarios.

**Comment by dtropp** [comment]
+1 for the above interpretation. I agree the code only implements cases 1,2,5.

I can't believe I only found this issue now. I've lost hours trying to work out why my styles.css file was being uploaded to S3 as 'text/plain'. Turns out the file command was returning 'text/plain', and the mime type by file suffix was returning 'text/css'. The comments imply the detector will return 'text/css' but of course the code is returning 'text/plain' (case 5).

**Option 1**
For now I have monkey-patched the ContentTypeDetector in my paperclip.rb initializer, but I'd love to know what a better solution is. In my case I am generating the file server-side so there is no risk of spoof attacks. 

**Option 2**
Perhaps a safer way would be to allow fuzzy matches, eg. when file command says 'text/plain' then accept mime-type of 'text/css', or when file command says 'application/zip' then accept 'application/msword', etc.

Given that you can't change the content-type after upload to S3 (without copying the s3 object), this seems like a real weakness in the current ContentTypeDetector.

**Comment by tute** [comment]
I just rejected code very similar to your suggestion in https://github.com/thoughtbot/paperclip/pull/1519, @josephbridgwaterrowe, because it would render paperclip insecure.

@dtropp, does the snippet in https://github.com/thoughtbot/paperclip/issues/1924#issuecomment-123919319 cover your case?

Thanks for your reports.

**Comment by tute** [comment]
Or the snippet in the README file? https://github.com/thoughtbot/paperclip#security-validations

**Comment by josephbridgwaterrowe** [comment]
@tute Thanks for your response, will you be updating the comment to reflect the actual behavior... or is there some misunderstanding in its behavior?

**Comment by tute** [comment]
> will you be updating the comment to reflect the actual behavior

We need to fix that code comment. Would you be willing to send a PR to do that? Thank you in advance.

**Comment by chrisdpeters** [comment]
@tute For those of us dying to see a resolution to this issue, can you explain _why_ @josephbridgwaterrowe's monkey patch is insecure?

I copied this module into a Ruby client that I'm building that must choose a proper MIME type to send as a header along with the file, and this immediately solved an issue with CSS files. I was also having a similar issue with the wrong MIME type being associated in S3.

Perhaps the monkey patch is acceptable when you're coding a client instead of a server though, but I'd be interested in learning more about why it renders a server-based application insecure. It _works_, but why is it not _right_?

**Comment by josephbridgwaterrowe** [comment]
@tute Yes I would be happy to submit a PR for that... if I understand correctly it would just be to remove point 3 from the bullets? Or would you like a more in-depth explanation of the behavior and why #3 is not applicable? I'm happy to do either, and I think an explanation to @chrisdpeters questions above would help me write the latter comment.

Thanks!

**Comment by tute** [comment]
> can you explain why @josephbridgwaterrowe's monkey patch is insecure?

The patch that's suggested is:

```diff
diff --git a/lib/paperclip/content_type_detector.rb b/lib/paperclip/content_type_detector.rb
index 782ed9e..5da99e7 100644
--- a/lib/paperclip/content_type_detector.rb
+++ b/lib/paperclip/content_type_detector.rb
@@ -32,8 +32,10 @@ module Paperclip
         EMPTY_TYPE
       elsif calculated_type_matches.any?
         calculated_type_matches.first
+      elsif possible_types.any?
+        possible_types.first
       else
-        type_from_file_contents || SENSIBLE_DEFAULT
+        type_from_file_command || SENSIBLE_DEFAULT
       end.to_s
     end
```

`type_from_file_contents` is replaced by `type_from_file_command`. It doesn't check with `mimemagic`, but it does with the `file` command. The only potential regression is around Open Office XML files, and that's not a vulnerability.

The `possible_types` method though runs `MIME::Types.type_for(@filepath).collect(&:content_type)`, which returns the mime type by only checking the file name. The issue is that by changing the file extension you can trick any file to be read as if it were of any format in paperclip, and that opens attack vectors. See for example: http://homakov.blogspot.com.au/2014/02/paperclip-vulnerability-leading-to-xss.html.

> Perhaps the monkey patch is acceptable when you're coding a client instead of a server though

When thinking about security, I'd personally rather "assume nothing". See https://twitter.com/SteveD3/status/729788140249092096 (couldn't find the brainier sources for this and have to move on).

**Comment by tute** [comment]
> if I understand correctly it would just be to remove point 3 from the bullets?

I didn't double check how the code comment doesn't actually describe the code, but we want to sync it up with the current behavior.

> Or would you like a more in-depth explanation of the behavior and why #3 is not applicable?

That too, in the commit message.

Thank you! :)

**Comment by SirRawlins** [comment]
This monkey patch solved me a bunch of issues today related to detection on JS and Font files, now correctly detecting. @josephbridgwaterrowe / @chrisdpeters - either of you ever feel comfortable running this in production? Or were the potential sec risks a problem?

**Comment by chrisdpeters** [comment]
@SirRawlins I opted to [remove spoof checking altogether](https://github.com/thoughtbot/paperclip/issues/1429#issuecomment-34390771). Tough decision, but my system needs to accept so many types of files, and the `file` command was failing on many of them.

I usually opt to leave the spoof checking in if the application needs to accept a few popular types of files (images, PDFs, etc.). But again, this particular app needs to accept all kinds of files.

**Comment by SirRawlins** [comment]
Thanks Chris, really appreciate the quick reply. I'm in a fairly similar
position to yourself so may look at that as an option.

**Comment by chrisdpeters** [comment]
@SirRawlins I will probably look at turning it back on later when I have the resources to actually handle all of the failures. I'm certainly not de-valuing the conservative approach that Paperclip has adopted.

**Comment by SirRawlins** [comment]
Yeah I agree Chris, I'd love to have it in place but for the moment just
don't have the time to dance around it.

Also I'm still running 3.x which is technically open to the same exploits
anyway so you could argue that I'll be no worse off :)

**Comment by josephbridgwaterrowe** [comment]
@SirRawlins yes we are running this in production, however it is an internal app so the security risks aren't really a big issue... To be honest, if it was an external app I don't think working around the possible security risks would be a big deal (but that may just be my naivety speak :wink:).

**Comment by josephbridgwaterrowe** [comment]
@tute, et al I realize I've been terrible in following through with any additional correspondence or submissions related to this issue. I have removed my thumb (from my butt) and would be happy to be more active in this matter... or has it been resolved now?

@tute I'm curious, if we were to change the comments on the file I assume that the problems we're having would continue?

Re: my monkey patch, my understanding is that it looks at the file name to determine its type and not the contents which is what renders it insecure. Could this patch be modified (using the same flow and commented cases) to determine the content type through the file contents (and thus mimemagic) rather than the file name?

**Comment by plicjo** [comment]
This is still a major pain point in 2017.

**Comment by ismailakbudak** [comment]
Same problem for .xlsx files
 It is working fine on local machine. 
But when I try on server, it uses application/zip for content_type. 

Monkey patched code block works fine in both environment

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.

**Comment by dougc84** [comment]
@mike-burns Interesting - is this due to `ActiveStorage`?  If so, will you have a migration guide?

**Comment by yusufRahmatullah** [comment]
I'm sad to hear that Paperclip has been deprecated.
This issue is caused by office open XML format which generated outside MS Office which has been solved by MimeMagic on [this changes](https://github.com/minad/mimemagic/commit/f4afc9bac944abe284d74e481ee08009e10b1564#diff-9cbf3a9b9596e476fac297ca438f961b)

**Comment by SanMane** [comment]
For me also @josephbridgwaterrowe's solution(Monkey Patch) worked better than the `Concern` solution. Thanks @josephbridgwaterrowe!! 👍
