### ISSUE TITLE
Name of the event that gets triggered after file creation?

### ISSUE THREAD

**Issue by dt1973** [thoughtbot/paperclip#1808]
Trying to delete some photos in Paperclip after they're converted to another format -- but what is the name of the event that gets triggered after the files are created in the file system?

Tried the `after_post_process` event, but it seems to get triggered before the file is created on the file system.

```
def on_after_post_process
  puts(self.attachment.path)
end
```

Prints:
```
=> "/home/user/rails-repo/public/system/photos/attachments//original/file.gif"
```

But actually the file was created at:
```
=> "/home/user/rails-repo/public/system/photos/attachments/000/000/<id>/original/file.gif"
```

Also tried the `after_create` event in ActiveRecord, but despite the correct file path, it seems to appear before the file gets created.

**Comment by jyurek** [comment]
The callbacks do get triggered after processing, but they trigger before saving. Paperclip handles the processing and saving separately. I'm confused as to why you don't see the file in the `after_create`, because it should definitely exist there. What does `path` report? What does the model's `attachment_file_path` hold?

**Comment by tute** [comment]
@dt1973 do you still need help with this issue? Will close for now as it's not a bug in the codebase, feel free to continue discussion. Thanks!
