### ISSUE TITLE
Rails 4, Paperclip 4.2.1 give error with binary file upload

### ISSUE THREAD

**Issue by rubyguy** [thoughtbot/paperclip#1842]
This is a major bug. Please see the thread below:

http://stackoverflow.com/questions/29934438/rails-4-paperclip-4-2-1-give-error-with-binary-file-upload/29946843#29946843

**Comment by tute** [comment]
Thanks for filing this issue! This is a bug indeed, awaiting a PR.

**Comment by jyurek** [comment]
I don't believe I follow what you're saying. You claim you have an upload problem, but the error you linked is a display issue because you're apparently trying to print your `params` to your view. And you're trying to upload an arbitrary binary file ending in `.tc` which is an uncommon ending, but adding that mapping apparently fixes the issue with the view?

**Comment by tute** [comment]
It seems like it, and in that case my previous comment is totally wrong.

**Comment by tute** [comment]
Closing as this doesn't seem like an issue with paperclip. If you think otherwise @rubyguy, please let us know and we'll address appropriately. Thanks!
