### ISSUE TITLE
Trying to setup paperclip gem locally

### ISSUE THREAD

**Issue by nathantechie9** [thoughtbot/paperclip#1879]
I am trying to contribute a fix to make paperclip work with the new AWS SDK v2. I am getting this.

uninitialized constant AWS::S3::Error::NoSuchBucket

**Comment by jyurek** [comment]
Please look into helping with #1730, which is already looking to add AWS v2 support.

As for the specific problem, I think that's because that error isn't defined in AWS v2 (or it is in AWS v2, but not in AWS v1, I forget). You'd need to remove references to that unless the correct gem version is available.

At any rate, I'm going to close this since you should help out and comment on #1730 instead. Thanks.

**Comment by nathantechie9** [comment]
I wrote a comment. It looks like paperclip will include s3 support built
into it? Instead of depending on the AWS S3 gem.
