### ISSUE TITLE
Save original file path for paperclip attachment in rails form

### ISSUE THREAD

**Issue by prodigerati** [thoughtbot/paperclip#1915]
I'm trying to save the original file path from the paperclip file attached in a rails form. I want to save it to the database for later use.

I read through the paperclip docs and can't find anything that I think will work. Ruby has a solution for File abstraction using `File.absolute_path` in the ruby-docs that I was able to get working in terminal but i'm not sure how to implement it with rails and paperclip in a form.

Any ideas would be appreciated...

Ultimately, the goal is to parse an xml file (nokogiri) and use the original file path to tell paperclip where to find the images listed in the xml which are in the same folder.

**Comment by jyurek** [comment]
If you mean you want to know that the file that you uploaded came from, say, `/Users/prodigerati/Photos/200141231/party.jpg` instead of just `party.jpg`, then I'm afraid to tell you that that information isn't passed along from the server.

However, if you're creating an API that you can use `curl` with, or something, and uploading files via script, you could pass along another parameter that the script populates. But that would be the only way off the top of my head to accomplish this. Sorry.
