### ISSUE TITLE
CSV upload: has contents that are not what they are reported to be

### ISSUE THREAD

**Issue by iashanmugavel** [thoughtbot/paperclip#1924]
I am getting this error while uploading csv file  in paperclip -v 4.3. For image files it is working.

Error: "has contents that are not what they are reported to be".

**Comment by chetan4664** [comment]
I am getting the same error while uploading images as well. 
gem 'paperclip', '~> 4.2.1'

If I use the latest version, it goes in an infinite loop !

**Comment by jyurek** [comment]
This is because it's hitting the media-type validation. This means that either the name or content type of the file being uploaded does not match the content type of the file as determined on the server. What is the name of the file you're trying to upload? Does it end in ".csv"? Are you using a custom server or hosting on heroku?

**Comment by iashanmugavel** [comment]
while uploading .csv file. It is not a content type validation. same file working well with paperclip 4.2.1.

**Comment by srogers** [comment]
I'm seeing the same thing with PDF attachments. Works fine with 4.2.1, but gets the "has contents that are not what they are reported to be" error in 4.3.  The error doesn't show up in dev environment where the attachment is being saved locally. It only happens in staging or production on Heroku where the attachment is being saved to S3.

**Comment by bwlang** [comment]
I see this problem for CSV files...  for uploads from chrome and ie on windows
see:
https://code.google.com/p/chromium/issues/detail?id=139105
reported there that this content type comes from the windows registry...
This is such a standard case that I don't think users should have to configure special mime types...

**Comment by sgringwe** [comment]
@bwlang i was able to fix a similar situation (csv files, windows) with this in the initializer:

```
comma_separated_values = MIME::Types["text/comma-separated-values"].first
comma_separated_values.extensions << "csv"
MIME::Types.index_extensions comma_separated_values
```

**Comment by bwlang** [comment]
@sgringwe 
Yes - your suggestion works... 
I did this instead;  (which avoids the deprecated index_extensions method)

  Paperclip.options[:content_type_mappings] = {:csv => "text/plain"}

However, I suspect this will bite almost anyone who want to handle csv file uploads from windows.  I'm thinking about how to reasonably make this a better experience for devs.

options that occur to me:
 - extend https://github.com/mime-types/ruby-mime-types/blob/master/type-lists/application.yaml to include csv for application/vnd.ms-excel 
 - modify paperclip to stop caring about application/* - not sure yet if this is a security problem (maybe we don't care if application a attempts to parse data from billed as application b)
 - code in this kind of special case to paperclip, maybe via some default content_type_mappings (undocumented config option used by media_type_spoof_detector) currently the default for content_type_mappings = {}, it could be {csv: 'text/plain'} - but this seems like a slippery slope toward reimplementing mime.types in paperclip.

Now that I think more about it... we should probably not be trusting anything the client has to say about the file type anyway (who's to say the client is friendly)
What about just comparing the results from `file` with the developer specified content type?
I'll submit a pull request to that effect unless I hear a better idea.

any other ideas?

**Comment by dcromer** [comment]
I also ran into this and fixed it using `Paperclip.options[:content_type_mappings]`

**Comment by latortuga** [comment]
Also seeing this error. We tried the fix suggested by @sgringwe and still had the same error on Windows. For now we just rolled back to a previous version.

@dcromer fancy seeing you in this thread!

**Comment by davbre** [comment]
I see the same message with webrick and nginx when uploading this json file, which contains embedded html:
http://data.okfn.org/data/core/airport-codes/datapackage.json

**Comment by johngibbons** [comment]
I'm running into this error when trying to generate the image from a url from Amazon S3:

          upload.image = URI.parse(URI.escape(upload.direct_upload_url))

It was working in 4.2.1.

**Comment by iashanmugavel** [comment]
@bwlang's solution works for `paperclip 4.3.0` also.

`Paperclip.options[:content_type_mappings] = {:csv => "text/plain"}`

**Comment by yordis** [comment]
@iashanmugavel I am getting this, so the suggestion is actually add the mapping to paperclip but I think this was working fine so why I should do this

**Comment by yordis** [comment]
@bwlang I tried your solution and didn't work for me. Basically I created a initializer file and added the config there

**Comment by yordis** [comment]
@jyurek sorry man, I still having this issue and it's with every type I used. Right now I am trying to upload `audio/mp3` file.

You say something about the content type. I had this content type for the file I am trying to upload `@content_type="application/octet-stream"`. Please I need help with this.

**Comment by metrue** [comment]
@yordis I am having this issue also, have  you fixed it?

**Comment by yordis** [comment]
@metrue nop, every single validation fail for me, no matter what type I used :disappointed:  and I can't rollback because `mongoid-paperclip` is locked :cry:

**Comment by metrue** [comment]
@yordis 

in my case, the validation for image works well, but for audio, like .mp3, it always meets this issue.
here is my validation condition:

```
  has_attached_file :avatar_img, :styles => { :medium => "300x300>", :thumb => "100x100>" },:default_url => "who.png"
  validates_attachment_content_type :avatar_img, :content_type => /\Aimage\/.*\Z/

  has_attached_file :introduction_audio, :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio', 'audio/wav' ]
  validates_attachment :introduction_audio, :content_type => { :content_type => ["audio/wav", "audio/mpeg", "audio/mp3"] }, :file_name => { :matches => [/mp3\Z/, /wav\Z/] }
```

**Comment by yordis** [comment]
@metrue try to use `validates_attachment_content_type

**Comment by martron** [comment]
I've hit this issue as well but with a user uploading a pdf (on Firefox/Windows).  Here's the log notice:

    [paperclip] Content Type Spoof: Filename aquamarine.pdf 
    ("application/pdf" from Headers, [#<MIME::Type:0x007fae154599b0 
    @content_type="application/pdf", @raw_media_type="application", @raw_sub_type="pdf", 
    @simplified="application/pdf", @media_type="application", @sub_type="pdf", 
    @extensions=["pdf"], @encoding="base64", @system=nil, @registered=true, @url=["IANA", 
    "RFC3778"], @obsolete=nil, @docs=nil>] from Extension), 
    content type discovered from file command: application/pdf. 
    See documentation to allow this combination.
To me it looks like the header's 'application/pdf' lines up with the Extension's 'application/pdf', so why does it think it's a spoof?  I was able to upload the file without issue with Chrome on Linux.

**Comment by martron** [comment]
Using

    Paperclip.options[:content_type_mappings] = {
      pdf: "application/pdf"
    }
Fixed the issue for my client.

**Comment by yordis** [comment]
@jyurek Dude any help with this? I can't upload `mp3` files and where `application/octet-stream` is coming from when I try to upload the `mp3`?

**Comment by adonaldson** [comment]
I was seeing this message in an app I was working on that had `do_not_validate_attachment_file_type` set - should the content spoofing code respect that setting or does it cover a slightly different use case?

**Comment by ruckus** [comment]
In this article (see the very bottom):

http://www.theregister.co.uk/2014/02/09/content_type_spoofing_bug_in_ror_paperclip/

There is this line:

> “Also starting at version 4.0.0, Paperclip has another validation that +cannot be turned off. This validation will prevent content type spoofing.”

This is crazy! For my app I only have trusted users (verified admins) uploading files, and its OK to upload arbitrary files. How can I disable this validation all-together?

**Comment by yordis** [comment]
@ruckus monkey patch this https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/validators/media_type_spoof_detection_validator.rb#L20

**Comment by joshRpowell** [comment]
I get the following spoof when uploading a .csv on -v 4.3.1 on Windows machines: 
````
Content Type Spoof: Filename xls-sample2.csv (application/octet-stream from Headers, [#<MIME::Type:0x007f099785cc88 @friendly={}, @system=nil, @obsolete=true, @registered=false, @use_instead="text/csv", @signature=false, @content_type="text/comma-separated-values", @raw_media_type="text", @raw_sub_type="comma-separated-values", @simplified="text/comma-separated-values", @i18n_key="text.comma-separated-values", @media_type="text", @sub_type="comma-separated-values", @docs=[], @encoding="8bit", @extensions=["csv"], @references=[], @xrefs={}>, #<MIME::Type:0x007f0995c175c8 @friendly={"en"=>"Comma-Separated Values"}, @system=nil, @obsolete=false, @registered=true, @use_instead=nil, @signature=false, @content_type="text/csv", @raw_media_type="text", @raw_sub_type="csv", @simplified="text/csv", @i18n_key="text.csv", @media_type="text", @sub_type="csv", @docs=[], @encoding="8bit", @extensions=["csv"], @references=["IANA", "RFC4180", "RFC7111", "{text/csv=http://www.iana.org/assignments/media-types/text/csv}"], @xrefs={"rfc"=>["rfc4180", "rfc7111"], "template"=>["text/csv"]}>] from Extension), content type discovered from file command: application/vnd.ms-excel.
````
I've tried the initializer: 
````
Paperclip.options[:content_type_mappings] = {
	:csv => "text/plain"
}
````
I've tried the attachment: 
````
validates_attachment :attachment,
    :content_type => { :content_type => ["image/png", "application/zip", "application/x-zip", "text/csv", "application/vnd.ms-excel", "application/vnd.ms-office"] }
````
any suggestions?

**Comment by zealous1** [comment]
This is still very buggy.

The question was raised several months ago; why are we listening to what the client has to say about the filetype? Simple MIME validation reveals that CSVs, correctly saved, are going to be "text/csv" or "text/plain" -- yet with content type validation, by default, we get THREE errors on CSV upload!

The initializer only takes care of the one of errors. Paperclip still says it's not a valid CSV type... so we must turn off file type validation completely? Seems like a horrible idea... I am going to test rolling back to an older version of Paperclip, as mentioned above.

**Comment by iashanmugavel** [comment]
Hi All,

Still I am facing this issue with paperclip 4.2.1(meanwhile tried with 4.3.0, then did rollback to 4.2.1 ).

I think, contributor added few MIME types in the latest version. But worth trying the below  work around which was added  by the contributor in paperclip wiki. It works with few MIME type deprecated warnings.

you may wish to add your custom extension to the list of file extensions allowed for your MIME type configured by the mime-types gem:

```ruby
# Allow ".foo" as an extension for files with the MIME type "text/plain".
text_plain = MIME::Types["text/plain"].first
text_plain.extensions << "foo"
MIME::Types.index_extensions text_plain
```

**Comment by rossinkiwi** [comment]
I had a similar problem with mp3 files being detected as Spoofs.
To fix it I had to add the following to config/environments/production.rb
` 
  Paperclip.options[:content_type_mappings] = {
    mp3: "application/octet-stream"
  }
`

**Comment by yordis** [comment]
@rossinkiwi just in case. Are you using Postman?

**Comment by rossinkiwi** [comment]
No.

**Comment by readmedia** [comment]
We also encountered this problem with a .XLS file. The file command returns:

```
$ file -b --mime test.xls
application/vnd.ms-office; charset=binary
```

However, MIME::Types returns:

```
> MIME::Types.type_for("test.xls").collect(&:to_s)
=> ["application/excel", "application/vnd.ms-excel"]
```

So this file is considered a spoof when it clearly is not. 

Now, I found that I can fix it by adding a custom mapping like so:

`> Paperclip.options[:content_type_mappings] = { :xls => "application/vnd.ms-office" }
`

...but how many more variants are we going to run into that will cause this problem? There probably should be an option for skipping the spoof check.

**Comment by wrkrb33** [comment]
I am running into this issue as regards .zip files.  So far the below is fixing it for me, but I won't be surprised if another variant of a zip mime type shows up.

    Paperclip.options[:content_type_mappings] = {
        zip: ["application/zip", "multipart/x-zip", "application/x-zip-compressed"]
    }  

I wonder if `Paperclip::MediaTypeSpoofDetector` isn't looking in too many places, as it tries to match content-types from headers, file inspection, and as implied from filename extension?  Wouldn't it be cleaner to simply rely on the results of file inspection?

**Comment by jake-007** [comment]
@ruckus and others in a similar situation–when only admins are authorized to upload anyways–here's a monkey patch _paperclip.rb_ initializer we use:
```ruby
module Paperclip
  # do not require any validations
  REQUIRED_VALIDATORS = []

  # do not complain when missing validations
  class Attachment
    def missing_required_validator?
      false
    end
  end

  # skip media type spoof detection
  module Validators
    class MediaTypeSpoofDetectionValidator < ActiveModel::EachValidator
      def validate_each(record, attribute, value)
        true
      end
    end
  end

end
```
Use with care.

**Comment by blackhatdigital** [comment]
Had the same problem added the following to a new paperclip.rb initializer: 

require 'paperclip/media_type_spoof_detector'
module Paperclip
  class MediaTypeSpoofDetector
    def spoofed?
      false
    end
  end
end

**Comment by jessielhh** [comment]
For the problem uploading CSV on Windows, I came up with the following solution:

add to the model:
`validates_attachment_content_type :my_csv_uploaded_file, content_type: 'application/vnd.ms-excel' `

and to the initializer:
`Paperclip.options[:content_type_mappings] = {
    csv: 'application/vnd.ms-excel'
}`

It worked for me. It was tested using Windows 7 Professional

**Comment by jasonfb** [comment]
please note that CSV files come through as ```application/octet-stream``` _if you don't have Excel install on your Windows machine_. Once you install Excel, your CSV files come trough as ```application/vnd.ms-excel```

**Comment by Nitin-Salunke** [comment]
@tute I guess the actualy problem is in running the file command used to discover the content-type.
Some how system in not able to find the 'file' executable, if we specify the command_path explicitly then it solves the issue.

http://stackoverflow.com/a/39173446/5031811

**Comment by gduprey** [comment]
After 16+ months, there is still no solution?  Why can't the option to disable the security/validation logic be added in.  It's an imperfect solution, but since it appears there is no perfect solution and actual implementers are likely to understand their use-case and exposure better, making such an option available at least allows windows users the basic option to upload CSV and other files.

**Comment by z-a-h** [comment]
I've added the code below to fix this bug and while it has removed the messages about 'File is invalid' and 'File content type is invalid', I still get the 'File has contents that are not what they reported to be'

model: 
```
validates_attachment_content_type :file, :content_type => ["text/plain", "text/csv", "application/vnd.ms-excel", "application/octet-stream"]
```

mime_types.rb initalizer:
```
comma_separated_values = MIME::Types["text/comma-separated-values"].first
comma_separated_values.extensions << "csv"
MIME::Types.index_extensions comma_separated_values
```

Paperclip initializer: 

```
Paperclip.options[:content_type_mappings] = {
  csv: ['application/vnd.ms-excel', 'application/octet-stream', 'text/csv', 'text/plain', 'text/comma-separated-values']
}
```

Any other suggestions?

**Comment by gduprey** [comment]
I implemented what jake-007 posted and it works (put it into a "paperclip.rb" file in the initializers directory).  It does yield a warning (about redefining a constant), but at least my users can upload files again.  Silly that you have to go to this extent so an end user can upload a file with this.

**Comment by z-a-h** [comment]
@gduprey that worked, thanks!

**Comment by rico-icecable** [comment]
My opinion is this (take it with a grain of salt, though, because I am probably missing some critical context, since I have no familiarity with Paperclip internals or it's history):

1. Rejecting uploads because the mime-type **as reported by the client** doesn't match the mime-type **as determined by the server** seems like the incorrect approach. If the server can determine what the actual mime-type is, then I don't think the mime-type reported by the client is actually useful, since it can't be trusted. Instead, I think the only matter of concern is:

  Is the mime-type **as determined by the server** a mime-type that we want to accept?

2. Having a validation that can't be turned off seems like a bad idea. I think enabling it by default is a good idea, but being able to turn it off is critical. After all, a developers using Paperclip understands their app and use case best and I think they should be allowed to ignore some strident warnings and turn the validation off if that's what they think is best for their situation.

---

I would be willing to help get a PR together for this if somebody who is more familiar with the codebase and architecture can point me in the right direction and perhaps enumerate some of the issues I should consider.

**Comment by pdfrod** [comment]
I think @rico-icecable comments are spot on: the MIME sent by the client can't be trusted and thus should be completely ignored, and there should be a way to disable the validation.

In my case, Firefox would sometimes set the MIME to `application/octet-stream` when sending an PDF. Although the file was a perfectly valid PDF, the spoof detector rejected the file because the browser said it was a `application/octet-stream` instead of a `application/pdf`. I don't care what the browser thinks the file is - if it's a valid PDF it should be accepted.

I was able to make it work for me setting the validation as follows:
```
validates_attachment :attachment, file_name: { matches: /\.pdf\z/ }
```

And adding the following in an initializer:
```
Paperclip.options[:content_type_mappings] = {
  pdf: 'application/pdf'
}
```

**Comment by SirRawlins** [comment]
Just as an aside, I'm also having type detection issues with webfonts `.eot` (which are detected as application/octet-stream) and minified javascript files `.min.js` (which are detected as text/x-csrc or text/x-matlab)

I've attempted the above approaches with the paperclip options and addition of the MIME::Types  in an initializer but this doesn't seem to make any difference.

```
Paperclip.options[:content_type_mappings] = { eot: "application/vnd.ms-fontobject"}
```

This has been an issue ever since 4.0.0 when changes were first made to the mime detection setup, currently holding me down at 3.x which is now causing problems with bringing Rails up to date.

Don't mind if hacks are quick and dirty, but would love to find a working option.

**Comment by SirRawlins** [comment]
Further hunting around seems that the monkey patch proposed in #1713 seems to get things working for me in the short term, although I appreciate it's not a problem workable option.

**Comment by dscott-soltech** [comment]
Still running into this -- still having to use the monkey patch.  Wish there was a better resolution...

**Comment by rystraum** [comment]
I'm not confident that my above PR will get merged, considering the maintainer's attitude towards security (as that setting will reduce security) but it should be better than having people monkey patching.

**Comment by NazmiAzzim** [comment]
using paperclip 5.0.0.. the weird part is there is no error yesterday with my code.. can upload images like it suppose to be.. and today, i run again.. this error of "Image has contents that are not what they are reported to be" occur, even with the same image i upload yesterday.. the problem solved after i add validate media type command:

    has_attached_file :image, { validate_media_type: false }

Even the problem solved, it still bugging me.. i don't do any changes yesterday. I run the same code and image.. suddenly got error

*sorry for my bad english ^^'

**Comment by jasonfb** [comment]
Was Microsoft Excel installed on either the computer from yesterday or today?

The MIME type is reported by your operating system. If you switch OSes, install Excel, etc, you could see a difference

**Comment by NazmiAzzim** [comment]
Nope. I installed Microsoft Excel about 6 month ago.

**Comment by NazmiAzzim** [comment]
Nope. I installed Microsoft Excel about 6 month ago. @jasonfb

**Comment by rolandoalvarado** [comment]
@jake-007 solutions saves me with regards to issue in .m4a file.

**Comment by MrEmelianenko** [comment]
lol, the birthday of this issue is approaching, let's make the party 🎉

**Comment by plicjo** [comment]
@MrEmelianenko yeaaaaaaah!

**Comment by dfabreguette-ap** [comment]
Same issue with Axlsx gem. File is created through the #serialize method. Using mongoid_paperclip gem.

**Comment by kerim** [comment]
Just encountered this error trying to import a follower list from g0v.social to mastodon.xyz (but it worked with an export from scholar.social...)

**Comment by codeodor** [comment]
Is there an official workaround for this?   I tried the suggestions above, and they don't seem to work on 5.0.

**Comment by dougc84** [comment]
I've been fighting with XLS and PPT files for two days now.  Seems to be an ever-present error with Paperclip.  I wish our production app didn't rely so much on Paperclip, or Paperclip didn't rely so much on MimeMagic (which is stale), but we can't get around it.

Paperclip team: this has been an issue that's gone back as far as 2015 on Github, as far as I can tell.  When will you all provide us some alternative ways of specifying mime types without having to monkey patch stuff (which always has unexpected results)?

**Comment by ghiculescu** [comment]
If anyone watching this thread is interested in putting together a PR (I think @rico-icecable's suggestion [here](https://github.com/thoughtbot/paperclip/issues/1924#issuecomment-251589305)) seems most promising, I'd be happy to sponsor its development.

**Comment by jasonfb** [comment]
@ghiculescu -- the never-ending MIME type issue with paperclip may one day see a fix? I never thought I'd live to see the day ;)

I corresponded on this issue (and ran into it) over several years. The *essence* of my understanding is that the client-side MIME reporting of the file's type can't actually be trusted, but the authors of the gem have make an implementation that explicitly has a philosophy that conflicts with this — it explicitly trusts client-side sent MIME types, and has a validation that cannot be turned off. (It's that last part that seemed most problematic to us, since turning off the client-side MIME validation seemed like a good work around to us.)

The only *true* fix is to actually somehow verify your file input *on the server side*. The MIME-type sent by the client is just a convenience but does little from a security perspective because it can be spoofed. 

So... i'd be happy to offer to work on this but I'd recommend the following:

1) the option to turn *off* the MIME type validation be added back into the gem if it hasn't already. (I think it was there, then got removed, etc)

2) there will be some added documentation that MIME-type detection is not foolproof, and does nothing from a security perspective, and that CSVs and other files have known quirks when using MIME-type detection (explained in copious detail across this issue). I will of course document the known-work arounds. 

do you think that direction would be welcomed by the gem's authors? I just don't want to start down a path if it is inconsistent with the philosophy of the gem.

**Comment by ghiculescu** [comment]
@jasonfb 

- I agree that paperclip should only care about the server-side MIME.

- I think if you add an option to disable, you need to very clearly explain the risks associated. Honestly I can't think of a good use case for disabling that can't be better solved by doing server-side MIME validation properly. My suspicion is that everyone who disables by monkey patching at the moment does so because client-side validation is always wrong for popular file types on popular operating systems. So if that problem goes away, the incentive to disable might go away too.

- re: added documentation, basically same as above. I would be interested to understand how important that is in light of paperclip doing validation in a more sensible way.

My understanding (or at least, my use case) is that point of all these checks to protect your app from someone uploading an exe but putting a .csv on the filename, because otherwise you might trust that file, and allow another user to download it, and then they would run the bad exe. As far as I can tell, all the problems come about when you do client-side MIME validation that catches this use case, but also catches legitimate CSVs for a multitude of reasons. If we remove client-side validation and just check on the server - and if this use case still works - then it should be happy days.

In terms of the gem's authors, I have no idea what their philosophy on this is. But I think the gem's userbase (or at least, me) are very keen for a proper solution here.

**Comment by rystraum** [comment]
@ghiculescu @jasonfb I made a PR a while back that is supposed to add an option to disable MIME-validation. However, one of the comments there is that it's already available on a per-model basis.

Here's the comment & my PR: https://github.com/thoughtbot/paperclip/pull/2378#issuecomment-338354751

I haven't verified the comment but perhaps it can help you.

**Comment by jasonfb** [comment]
👍  is there a good option out there for doing the server side validation that you know of? (like an existing gem) I'm just thinking out loud here but thinking how we could point someone in the right direction for "doing server-side MIME validation properly" as you say.

**Comment by toasterlovin** [comment]
If this is still open in a couple of months, I'll take a crack at it then. In the meantime, if anybody is going to tackle it now, the README has a bit of text that suggests Paperclip already does server side MIME type checking:

> `Paperclip::ContentTypeDetector` will attempt to match a file's extension to an inferred content_type, regardless of the actual contents of the file.

That is at the very bottom of the [Validations section](https://github.com/thoughtbot/paperclip#validations).

**Comment by park9140** [comment]
Random thought.  Reading through alot of the error reports seem to be windows application based things.  Is it possible the detector just needs to ignore the byte order mark at the beginning of some windows files?  I ask because I'm getting a similar issue to this when uploading an svg file with a BOM on it.   It only happens when I'm using the google cloud file storage and not when I'm storing to my local file system in dev.

**Comment by hiphip90** [comment]
OK, so I had the same problem, but with JSON files with .json extension. 

`file` utility reported MIME type to be `"text/plain"`, while `mime-types` gem said it was `"application/json"`. Comparison happens in `media_type_spoof_detector.rb` file on 41 line. 

So, two possible solutions:
1) Add `"json"` to list of extensions for `"text/plain"` type (this is what I ended up doing):

    ```ruby
    plaintext = MIME::Types["text/plain"].last
    plaintext.extensions = (plaintext.extensions << "json")

2) Use /etc/magic to define rules for `file` utility to correctly detect json MIME types.

**Comment by jasonfb** [comment]
@hiphip90 the MIME type comes from the browser, not detected on the server. Several others I think have come before you with same confusion because it is not intuitive. The proble is what the browser sends which we cant control in the wild

**Comment by jasonfb** [comment]
Yes .json should be in allowed extensions list for the text/plain type that is :+1:

**Comment by hiphip90** [comment]
@jasonfb This is not true in general, and especially not true in my particular case since I upload from my backend code, this is not some user's attachment I'm talking about.

If you look closely in the code within the file I've mentioned, you can actually see that there are two checks for spoofing performed. 

First compares MIME detected by `mime-types` gem with the one provided with the file either by the browser, as you suggested, or any other way.  The gem performs it's check based on a file extension, and it considers anything with .json extension to be of `"application/json"`

The second one compares what mime-types returns with what file utility returns, which is `"text/plain"` for json, so this is absolutely server-side. If any of the two fails, spoofing error is added to the model. 

So in this particular case I believe this is mime-types failure two acknowledge the fact that it does not comply with what widely-used file util returns for JSON file type.

**Comment by jasonfb** [comment]
Ah yes I see the code you are referring to. Nonetheless, this issue, which is years and years old, is related to the incorrect passing of the MIME-type by the browser, which is the root of the CSV problem. I think your problem is different.

**Comment by hiphip90** [comment]
@jasonfb Indeed it is, but most questions regarding problems with MIME types and paperclip uploads get redirected to this thread, so I think it may be helpful to someone struggling with the same JSON upload problem :)

**Comment by JerryGreen** [comment]
Got this error too. I'm just parsing all my email box via IMAP and saving all its attachments. I don't want to validate shit.

Stacktrace:

```
Command :: file -b --mime '/var/folders/1n/_3wfw7dx3mbcydb6wzj2m58r0000gn/T/976f2abf208a5b5a5dd8dd8ca8722f0020180312-35380-1j13iq3.SC2Replay'
[paperclip] Trying to link /var/folders/1n/_3wfw7dx3mbcydb6wzj2m58r0000gn/T/976f2abf208a5b5a5dd8dd8ca8722f0020180312-35380-1j13iq3.SC2Replay to /var/folders/1n/_3wfw7dx3mbcydb6wzj2m58r0000gn/T/9dbc59ffa4116b22bc89b579a5754b1f20180312-35380-11bzvuf.SC2Replay
Command :: file -b --mime '/var/folders/1n/_3wfw7dx3mbcydb6wzj2m58r0000gn/T/9dbc59ffa4116b22bc89b579a5754b1f20180312-35380-11bzvuf.SC2Replay'
[paperclip] Content Type Spoof: Filename Ruins_of_Endion(66).SC2Replay (application/octet-stream from Headers, [] from Extension), content type discovered from file command: application/octet-stream. See documentation to allow this combination.
[paperclip] Trying to link /var/folders/1n/_3wfw7dx3mbcydb6wzj2m58r0000gn/T/976f2abf208a5b5a5dd8dd8ca8722f0020180312-35380-1j13iq3.SC2Replay to /var/folders/1n/_3wfw7dx3mbcydb6wzj2m58r0000gn/T/9dbc59ffa4116b22bc89b579a5754b1f20180312-35380-3pz8se.SC2Replay
Command :: file -b --mime '/var/folders/1n/_3wfw7dx3mbcydb6wzj2m58r0000gn/T/9dbc59ffa4116b22bc89b579a5754b1f20180312-35380-3pz8se.SC2Replay'
[paperclip] Content Type Spoof: Filename Ruins_of_Endion(66).SC2Replay (application/octet-stream from Headers, [] from Extension), content type discovered from file command: application/octet-stream. See documentation to allow this combination.
[paperclip] Trying to link /var/folders/1n/_3wfw7dx3mbcydb6wzj2m58r0000gn/T/976f2abf208a5b5a5dd8dd8ca8722f0020180312-35380-1j13iq3.SC2Replay to /var/folders/1n/_3wfw7dx3mbcydb6wzj2m58r0000gn/T/9dbc59ffa4116b22bc89b579a5754b1f20180312-35380-ia3miw.SC2Replay
Command :: file -b --mime '/var/folders/1n/_3wfw7dx3mbcydb6wzj2m58r0000gn/T/9dbc59ffa4116b22bc89b579a5754b1f20180312-35380-ia3miw.SC2Replay'
[paperclip] Content Type Spoof: Filename Ruins_of_Endion(66).SC2Replay (application/octet-stream from Headers, [] from Extension), content type discovered from file command: application/octet-stream. See documentation to allow this combination.
```

In my model I have:
```
  has_attached_file :file
  do_not_validate_attachment_file_type :file
```

Very confusing. `{ validate_media_type: false }` not helping.

> See documentation to allow this combination

Which documentation and how do I allow this?

P.S. it's just an old starcraft2 replay from old popular player Brat_OK, so no any spoofing here, lol

**Comment by JerryGreen** [comment]
Hmmm, got this!
It works with that:

```
require 'paperclip/media_type_spoof_detector'
module Paperclip
  class MediaTypeSpoofDetector
    def spoofed?
      false
    end
  end
end
```

**Comment by mike-burns** [comment]
Looks like we found a workaround, closing.

**Comment by codeodor** [comment]
Can you say what the official workaround is?  Thanks!

**Comment by mike-burns** [comment]
No official workaround; I was referring to https://github.com/thoughtbot/paperclip/issues/1924#issuecomment-372150618 .

Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue further.

**Comment by Skipants** [comment]
Sorry for the thread revival but I'm still running into this in 2019.

Please don't use that "workaround". It opens up ANY uploads to content spoofing without warning to anyone else using `has_attached_file` in your app.

`validate_media_type: false` option on the `has_attached_file` class method _should_ work, although it once again does open you up to spoofing. It's a great option though since it's explicit about it. Although it didn't work for https://github.com/thoughtbot/paperclip/issues/1924#issuecomment-372149537 which is strange. It looks like it explicitly avoids the validation in `has_attached_file.rb`

The real problem is `content_type_detector.rb` uses 3 different ways to determine the content type of the file:

1. If there's a file name, it uses the `MIME::Types` class from, I'm assuming, the `mime_types` gem to determine the content type.
2. If there's no file name, it tries to determine it from the file contents using `MimeMagic`. And if `MimeMagic` doesn't find it it then uses the `file` shell command.

Then, in MediaTypeSpoofDetector, there's `calculated_type_mismatch?` which straight up does not work for some content types. It compares the results of `Mime::Types` to the `file` command. And those two implementations are not always in sync: eg. JSON returns `application/json` from Mime but `text_plain` from the `file` command.

The workaround is to provide an override that matches the `file` command, since that's what it checks in `MediaTypeSpoofDetector#mapping_override_mismatch?`. So for JSON, that would be `text/plain`:

```ruby
Paperclip.options[:content_type_mappings] = {
  json: %w(text/plain),
}
```

**Comment by dougc84** [comment]
@Skipants you may still be running into this in 2019, but you aren't going to see an update because Paperclip is deprecated in favor of ActiveStorage.

https://robots.thoughtbot.com/closing-the-trombone

**Comment by Skipants** [comment]
I'm working in a legacy codebase, unfortunately.

**Comment by Sanjit-Prasad** [comment]
> lol, the birthday of this issue is approaching, let's make the party 🎉

Again approaching soon!

**Comment by jasonfb** [comment]
hi @Sanjit-Prasad ! You know I'm on Active Storage now and it works fine. it's funky with the strange naming conventions but I'm happy with my implementation. 

reads up my CSV generally no problem and not has buggy as I remember paperclip was. But paperclip was a great tool in its day.

**Comment by peterwake** [comment]
FWIW, I spent an age working with a CSV file uploaded that had been saved using Excel on Mac as a UTF-8 file.

After digging around in the mime gem, I found I could add

```ruby
MIME::Types.add(MIME::Type.new(['application/csv', 'csv']), true)
```

**Comment by lrworth** [comment]
This horse is super dead already, but for anyone who cares: [the next release of `file` will give `text/csv` for CSV files](https://bugs.astron.com/view.php?id=174) which should fix this problem.
