### ISSUE TITLE
MIME Type Spoof Detecting not working with spoofed gifs.

### ISSUE THREAD

**Issue by Wingar** [thoughtbot/paperclip#1941]
Hi,

I recently discovered that the content_type anti-spoof isn't working on gifs spoofed as png or jpg. I discovered this in production, I recently had to temporarily ban gifs from avatars because of a possible fault so I changed to my content_type validator to: `content_type: ['image/jpeg', 'image/png', 'image/bmp']`. When uploading a normal gif, it rejects as it should. However, if a gif is renamed to be a .png file, it uploads just fine. Verified in both development and production environments. 

Now, here's the strange part, as far as I know the spoof detection is done by both the MimeMagic gem and the `file` command, yes? Well, running any file through both of these manually correctly identifies the file as gif. 
Also, when looking at the logs, during an upload to S3 the original image has content_type marked as image/jpeg or png, yet any resize is marked as image/gif. ImageMagick even resizes them correctly as gifs.

I'll be happy to post any relevant parts of the application if need be.

**Comment by tute** [comment]
Thanks for reporting @Wingar! More details, and even a bug fix couldn't be more appreciated. What version of paperclip are you using? Thank you!

**Comment by jyurek** [comment]
The issue here is that the spoof detection is done by the media type which, for images, are all the same (the `image/` part of the content type). This is done specifically because of things like this. In many cases, people will have gifs from (say) imgur that are named `.jpg` or vice versa. There is no inherent spoof-related problem in allowing a gif to be uploaded when a jpeg is expected, since one cannot be used to exploit the other. That plus the fact that it reduces confusion greatly on the part of the users gave us the reason to do it this way.

This could be considered a bug in the content type validations because we're, again, trusting the browser's detection instead of calling `file` ourselves. I would be open to PRs to change that.

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
