### ISSUE TITLE
url being escaped differently or am i using unsupported functionality?

### ISSUE THREAD

**Issue by pkmiec** [thoughtbot/paperclip#1945]
After I upgraded paperclip from 4.2.0 to 4.2.2, my urls are escaped badly,

`/photos/1.jpg%3Fstyle=medium?1437673880`

Note, I use custom interpolator for my url (`:url => ":url_with_style_as_param"`),

```ruby
def url_with_style_as_param(attachment, style_name)
  style_param = default_style?(attachment, style_name) ? "" : "?style=#{style_name}"
  ext = extension(attachment, style_name)
  file_ext = [".", ext].join("") unless ext.blank?
  "/#{attachment.instance.class.name.tableize}/#{attachment.instance.id}#{file_ext}#{style_param}"
end
```

I looked at the paperclip code and I am wondering whether my type of interpolator (one that puts parts  into the params) is actually supported?

**Comment by tute** [comment]
@pkmiec have you found a fix or workaround to this issue?

**Comment by pkmiec** [comment]
@tute no, we don't. i think we will change our ways and stop using the query params.

**Comment by tute** [comment]
> I looked at the paperclip code and I am wondering whether my type of interpolator (one that puts parts into the params) is actually supported?

@jyurek: is @pkmiec using something not supported, or was a bug introduced in between 4.2.0 and 4.2.2?

**Comment by jyurek** [comment]
Part of generating a url is that characters that are unsafe for urls get escaped. Paperclip expects that the data you get in your `url` does not include url-specific characters like `?`. Escaping here makes sure things like files named `?.jpg` don't confuse browsers.

I would make the recommendation that you add a route that supports putting the style into the url itself, instead of having it be a query parameter.
