### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by maclover7** [thoughtbot/paperclip#1973]
Not sure if any breaking changes that are upcoming in Rails 5 affect Paperclip, but it's important that the project is adapted if any changes are needed. @jyurek, will we be deprecating Rails 3.2 support when Rails 5 is released?

**Comment by jyurek** [comment]
Yeah, I'd say we should. There are lots of Rails 3.2 projects out there, but we shouldn't hold things back because of them. And they can use older versions of Paperclip anyway.

Can you do a cursory check by adding a new Appraisal and seeing if there are any glaring breakages to get the ball rolling?

**Comment by maclover7** [comment]
:+1:. Will send in a PR.

**Comment by tute** [comment]
Thanks for this initiative @maclover7! Let's work on the PR, closing in favor of #1976!
