### ISSUE TITLE
validates_attachment_file_name using wrong extension from remote url

### ISSUE THREAD

**Issue by meliborn** [thoughtbot/paperclip#1978]
I have fallowing rule:
```validates_attachment_file_name :image, :matches => [/png\Z/i, /jpe?g\Z/i]```
But when I trying to do this:
```Photo.create! image: URI.parse(remote_url)```
Where remote url is ```http://example.com/watermark/_watermark.php?img=/full_87e0105fdc8c65b8a28d0e8ad373436e.JPG```
I getting validate error. As I understood, it thinks that the image has ```.php``` extension instead of ```JPG```

**Comment by jyurek** [comment]
That's because the path ends in is `_watermark.php`. The `.JPG` is part of a query parameter, not part of the path of the URL. You could either add URL rewriting on the watermark server's side to transform URLs that would work into the form you have here, or (if you don't have control over that server), you could write a new Adapter that will take the URL parameters into consideration.
