### ISSUE TITLE
EPS raises huge error about content type

### ISSUE THREAD

**Issue by doits** [thoughtbot/paperclip#1979]
Using Paperclip version 4.3.0.

I'm trying to attach this EPS picture: https://gist.github.com/anonymous/0c81a6284a1c0c3a7ce8
When doing so, I get a huge error from paperclip: https://gist.github.com/09e964ed63647b0d9e5c

I try it like this in console:

```
model.company_logo = File.open('/tmp/bla.eps')
```

I've temporarily disabled validation in my model (`do_not_validate_attachment_file_type :company_logo`), but still the same.

When looking at `MIME::Types["application/postscript"].first.extensions` it gives `["ai", "eps", "ps"]`, so why doesn't it allow it even the file has the extension `.eps`? And why is the error message of paperclip so huge?

**Comment by jyurek** [comment]
I don't know why the error is so huge. That is a damned log message though!

As for the error, it seems that your browser is saying that the content type of the file is `"image/x-eps"` which is not one of the types that `.eps` resolves to. However, since mime/types recognizes `eps` as an extension for `application/postscript` and so does `file` it should be ok. I'll have to look into this.

**Comment by jyurek** [comment]
FTR, `do_not_validate_attachment_file_type` does not disable spoof checking. It just relaxes the requirement to have a `content_type` or `file_name` validation.

**Comment by jyurek** [comment]
This is supposed to be happening (well, not the huge log line, but the failure is). All of these three things have to match up: The supplied type from the browser, the type based on the name, and the type based on the `file` command. Since you only have two out of three, you're running afoul of the spoof checker. You can either turn off spoof checking by adding `media_type_validation: false` to your attachment definition, or you can explicitly allow `image/x-eps` as a valid type by following the directions here: https://github.com/thoughtbot/paperclip#security-validations. I hope this helps.

**Comment by doits** [comment]
Thanks for explanation, but I still cannot get it to work :-(

> All of these three things have to match up: The supplied type from the browser, the type based on the name, and the type based on the file command.

I am not using any browser to upload the file, so only two things have to match up now? Namely type based on name and type based on file?

My first try to disable media type validation:

```
has_attached_file :company_logo, media_type_validation: false
```

No change. Second try to register `image/x-eps` as a valid mime type:

```
# Rails initializer
Mime::Type.register 'image/x-eps', :eps
```

But it looks like this does not have any effect on  `MIME`:

```
MIME::Types["image/x-eps"]
=> []
```

So I cannot add any extensions to it like written in the readme.

What am I doing wrong?

**Comment by doits** [comment]
Finally got it to work by stumbling on this:

```
Paperclip.options[:content_type_mappings] = {
  eps: 'application/postscript'
}
```
