### ISSUE TITLE
Remote URLs with dots in URL

### ISSUE THREAD

**Issue by jeroenhouben** [thoughtbot/paperclip#1999]
Remote files being served from some dynamic image content server can be problematic.

Example:
```
http://banners.knollenstein.nl/adnetwork/servlet/advertBeans.GetImageServlet?image=6517136507BF5D4AC1257C7100313CDD-128x60-r-t-1.jpg
```

Paperclip will think the file is called `advertBeans.GetImageServlet` and thus flag it as having a non matching mimetype/extension.

**Comment by colinmacritchie** [comment]
Having issue with remote urls myself. Very frustrating.

**Comment by colinmacritchie** [comment]
Can we get this as a priority, need to be able to use url uploads.

**Comment by jyurek** [comment]
Paperclip is not identifying the file has `advertBeans.GetImageServlet` because of the dot. It's doing is because that is the end of the path portion of the url. If there were no dot it would do the same. It does not and cannot know that the name is actually in the `image` query parameter.

If you need to change this, the best course of action would be to make a subclass of `Paperclip::UrlAdapter` and augment the `cache_current_values` method to extract the name of the file as you expect it.

**Comment by jeroenhouben** [comment]
Thanks @jyurek .

I think a much quicker / better option (for me anyway) would be to just have Paperclip look at the actual *contents* of the file and then decide if it's of a valid type. But I couldn't find a way to configure this behaviour when using remote URLs, or was I missing something?
