### ISSUE TITLE
Files are not being deleted if transaction rollback

### ISSUE THREAD

**Issue by salmanasiddiqui** [thoughtbot/paperclip#2008]
On transaction rollback while updating a record or creating, attached file is not being deleted.
Im using aws s3 as storage. Paperclip 4.3. Rails 4.2.

I found that this was intentionally implemented in this gem (https://github.com/thoughtbot/paperclip/pull/1371).

Is this configurable? to delete or keep file if the record is not saved?

**Comment by cheerfulstoic** [comment]
I was looking for the same thing and I found that test as well.  I think maybe you have the same confusion that I had about the test.  The test is making sure that if you `delete` within a transaction that the stored paperclip file won't be deleted (because the DB record is still going to be around)

But I think what you and I would like is the ability to have the file deleted `after_rollback` if we're trying to create/update but things fail.  Is that correct?  As far as I can tell, this isn't implemented

**Comment by sergio-bobillier** [comment]
I agree this is a must have feature, because the images from failed transactions stick around taking up disk space. It is also necessary that when updating a record attachment the current file is not replaced until the transaction is committed.

Right now if you replace an attachment and the transaction fails the new image is saved and the old one is deleted then on rollback the record field is set back to the old value. So you lost the original attachment forever and you now have a file which is not referenced by any record on the disk. Basically garbage.

**Comment by salmanasiddiqui** [comment]
@cheerfulstoic ahh yes. I think I referenced #1371 incorrectly. Infact that PR can be used as a solution, what @krzychk did for preventing deletion of files if transaction rollbacks on destroy, the same can be done for preventing creation of files if transaction rollback on create/update.

**Comment by mike-burns** [comment]
Thank you for the feature request. Unfortunately we will be deprecating Paperclip and therefore will no longer be accepting new features.
