### ISSUE TITLE
processors options not used if styles are empty

### ISSUE THREAD

**Issue by jonathantribouharet** [thoughtbot/paperclip#2009]
Hi,
I use a custom processors for superposing image and the processor is called only if I have declared a styles options.

```
has_attached_file :media, processors: [:my_processor] # doesn't work
has_attached_file :media, processors: [:my_processor], styles: {nothing: 'true'} # work
```

**Comment by greggawatt** [comment]
Do you mind posting ```:my_processor``` so i could test this out? What is the exact error you're getting?

**Comment by paulriddle** [comment]
It happens because style options is not optional, here it is mentioned in the README:

*NOTE: Because processors operate by turning the original attachment into the styles, no processors will be run if there are no styles defined.*

In some cases this might not be what you want. I think it's reasonable in the absence of styles to still run the processor, but only with one style called 'original'. It would also be useful to allow specifying styles as an array of stylenames because some of the custom processors are not meant to be customized.

**Comment by jonathantribouharet** [comment]
Thank's I didn't see the note.
