### ISSUE TITLE
Paperclip::AdapterRegistry::NoHandlerError when updating a model

### ISSUE THREAD

**Issue by alereisan** [thoughtbot/paperclip#2041]
In my User.rb Model I have attached a photo with paperclip. Generally there is no problem with it and everything works fine, the photo gets uploaded, processed by paperclip and the url saved to the db.

But when I try to update other fields of the User Model with a separate form, let's say I want to Update the first_name and last_name and username, I get this error:

```

Paperclip::AdapterRegistry::NoHandlerError (No handler found for "/system/users/photos/000/000/001/original/picture?1447029598"):
  app/controllers/users_controller.rb:17:in `update'
```

I guess that Paperclip tries to process the image which is already in the database again. 

This results in an error 500. and I can't update the User model.

Any fix for this?

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand your issue in order to help you.

Sorry we don't have the time now to help you with this question, and thanks!

**Comment by emico7** [comment]
> Also, I recommend you follow the steps outlined in http://....

@tute I was googling for a similar error today and got to this page. As of today, the second link you included in your comment above (re: bug report) redirected me to a very inappropriate site. 

I know it's an old post but just thought that I'd report it.

**Comment by tute** [comment]
Aw, bummer! Thank you, I edited it out.

**Comment by tute** [comment]
It appears in so many places in GitHub!! What can we do about that now NSFW domain it used to be useful in Open Source, @derekprior? And hi, BTW! I hope you are doing fine! 😃 👋
