### ISSUE TITLE
Attachment path when switching type column of STI model

### ISSUE THREAD

**Issue by chrisjeon** [thoughtbot/paperclip#2073]
Hi there,

This is more of a question rather than a bug (maybe if there's no solution to it, it could be a feature added to future versions of paperclip).

Let's say that we have a Single Table Inheritance (I'll just use the short-hand STI from now on) models `ResourceDocument` and `ResourcePDF` that both inherits from `Resource` model. `ResourceDocument` model was in production for quite some time and all document files (including pdf files) were saved as `ResourceDocument`s. Let's say that we now have a new requirement that prompted us to add the `ResourcePDF` model and we need to migrate over the pdfs that were previously saved as `ResourceDocument` into `ResourcePDF`s.

This seems easy to do with a simple migration or even a SQL statement. But it seems that due to the way paperclip sets the path names, once we write a migration like
```ruby
ResourceDocument.where('name ILIKE ?', '%.pdf').update_all(type: 'ResourceDocument')`
```

either of the two above updates the type column properly and the pdf files are now classified as `ResourcePDF`s. But unfortunately, the files themselves seem to unlink due to the way paperclip generates the path for the attachments.

For example, if I change one `ResourceDocument` that had a file url of (stored on S3 in my case, but I guess it doesn't matter where it's stored) `/resources/resource_document/asdf.pdf`, this will now change to `/resources/resource_pdf/asdf.pdf`. This is an incorrect url that will break the links on the pages for the users.

Is there a method on paperclip or a standard way of migrating the files over while running the migrations to move over STI models? Or do we have to write a script to do this manually?

Thank you for reading over this long issue.

**Comment by sikachu** [comment]
With a migration like this, I think you'll need to update the interpolation as well because you really can't rely on [`class` interpolation](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/interpolations.rb#L91-L94) anymore. 

I think it should be as easy as hardcoded the word `resource_document` in the `path` configuration of `has_attached_file` though.

I'm going to close this issue, but please let me know if that helps or not, or if you have any other questions.
