### ISSUE TITLE
asset_file_size (and other attributes) set to nil once paperclip's before_destroy hook runs

### ISSUE THREAD

**Issue by samkelly** [thoughtbot/paperclip#2088]
This creates a very precarious situation where if as an app developer you want to find out the asset_file_size right before you delete a file, you have to have your hook load before paperclip's. I don't even understand why it needs to set this to nil in the first place if the record is just going to be deleted shortly anyway...

**Comment by sikachu** [comment]
@samkelly we do rely on `_file_name` data to see if attachment exists or not. Clearing out those fields has to be done in the `before_destroy` hook since that's when record is going to be written to the database. If we are to do it in `after_destroy`, that will result in multiple SQL statements for one record.

However, I think that field should still be tracked by Active Model's dirty tracking. Have you tried to access the `_file_size` by using `_file_size_was`? (For example, `#asset_file_size_was`)

**Comment by tute** [comment]
@samkelly is this still an issue for you? Do you think it needs a change in paperclip? Thanks!
