### ISSUE TITLE
How to optimize existing image using paperclip ?

### ISSUE THREAD

**Issue by ved54321** [thoughtbot/paperclip#2112]
Is there any method to optimize existing image which i have uploaded without using paperclip optimizer .For the new image i am using paperclip optimizer to optimize and also is there any way we can check image is already optimized or not. please help ?

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand your issue in order to help you.

Sorry we don't have the time now to help you with this question, and thanks!
