### ISSUE TITLE
attachment folder not created

### ISSUE THREAD

**Issue by aashish** [thoughtbot/paperclip#2165]
Hi, I am using rails 3, adding the attachment by creating TempFile and writing content to file 

```
    tmp = Tempfile.new('test')
    tmp.write("some large data in MB")
    class << tmp
      attr_accessor :original_filename
    end
    tmp.original_filename =
      "latest_test.csv"
    self.attachment = tmp
    self.attachment_content_type = 'text/csv'
```
and saving object.
The above code sometimes not creating file but the attachment attributes are saved. 

Not sure, If its a bug on paperclip. 
If its not a bug on paperclip. Is their a way to check if file exists or created and then save the object.

Thanks,
Aashish

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention
from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand your issue in order to help you.

Thanks, and sorry we don't have the time now to help you with this question.
