### ISSUE TITLE
Exclusive file format is not acceptable

### ISSUE THREAD

**Issue by starkshaw** [thoughtbot/paperclip#2189]
I have:
`app/model/track.rb`
```
class Track < ActiveRecord::Base
  has_attached_file :track
  validates_attachment_content_type :track, content_type: ["audio/mpeg", "audio/mp3", "audio/x-aiff", "audio/aiff", "audio/wav", "audio/x-wav", "audio/aac", "audio/mp4", "audio/mpeg4-generic", "audio/MP4A-LATM", "audio/aacp", "application/m4a", "audio/3gpp", "audio/3gpp2", "application/aac"]
  validates_attachment_file_name :track, matches: [/aif\Z/, /aiff\Z/, /wav\Z/, /m4a\Z/, /aac\Z/, /mp3\Z/]
  belongs_to :user
end
```

`config/initializers/paperclip.rb`
```
Paperclip.options[:content_type_mappings] = {
  aac: %w(audio/aac)
}

Paperclip.options[:content_type_mappings] = {
  m4a: %w(audio/mp4)
}
```

But the upload cannot be completed when I trying to upload an `.aac` file.

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand your issue in order to help you.

Sorry we don't have the time now to help you with this question, and thanks!
