### ISSUE TITLE
Paperclip::AdapterRegistry::NoHandlerError

### ISSUE THREAD

**Issue by webmaster219** [thoughtbot/paperclip#2265]
Hi,
I'm using now Paperclip and DropzoneJS in nested form.
DropzoneJS sends file using ajax but I got this error.
So How can I solve this issue?

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand your issue in order to help you.

Sorry we don't have the time now to help you with this question, and thanks!
