### ISSUE TITLE
Paperclip overrides supplied content type.

### ISSUE THREAD

**Issue by kwbock** [thoughtbot/paperclip#2276]
Given the following model
```
class MyModel < ActiveRecord::Base
  has_attached_file :attachment, presence: true, file_name: { matches: [/csv\Z/] }
  validates_attachment_content_type :attachment, content_type: "application/octet-stream"
end
```

The following code does not work
```
MyModel.create(attachment: file, attachment_content_type: "application/octet-stream")
```

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand your issue in order to help you.

Sorry we don't have the time now to help you with this question, and thanks!
