### ISSUE TITLE
image not working (no route matches) on Ubuntu 16.04

### ISSUE THREAD

**Issue by vhilly** [thoughtbot/paperclip#2294]
I have tested my app in ubuntu 14.04 uploaded images are showing but when I run it on ubuntu 16.04 on digitalocean server any uploaded images not showing up in both development and production env.

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand your issue in order to help you.

Sorry we don't have the time now to help you with this question, and thanks!
