### ISSUE TITLE
Should retry upload on AWS::S3::Errors::InternalError

### ISSUE THREAD

**Issue by thegedge** [thoughtbot/paperclip#2315]
As per [S3 Error Best Practices](http://docs.aws.amazon.com/AmazonS3/latest/dev/ErrorBestPractices.html), upload can be retried on an `InternalError`.

**Comment by janko-m** [comment]
@thegedge According to [aws-sdk docs](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#initialize-instance_method), 500 errors (which should include `InternalError`) should be retried up to 3 times. So it could be that `InternalError` was raised in your app because it occurred even on 3rd retry.

**Comment by thegedge** [comment]
Ah, that's quite possible. I don't think there were any logs to indicate what actions were taken, so I can't verify. It's pretty rare, but I'll keep an eye on it.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
