### ISSUE TITLE
custom folder to store attachments?

### ISSUE THREAD

**Issue by siegy22** [thoughtbot/paperclip#2320]
Is there a way to store the attachments somewhere else than in `public/system/...`?

I tried this line: 

``` ruby
Paperclip::Attachment.default_options[:path] = ":rails_root/public/my_sub_folder:url"
```

When storing, there does not seem to be a problem. However, when accessing it with the following this is what I get:

``` ruby
example.logo.url(:medium)
# => "/system/...." 
```

But it should be `"/my_sub_folder/system/..."`.

I can't find any documentation on this sorry.

**Comment by ayrat555** [comment]
maybe creating symlink in your file system that points to necessary directory will solve the problem?

**Comment by siegy22** [comment]
That would be a dirty hack and does not work in my case (I'm doing complex stuff with rewrite rules and vhosting..), but thanks for the idea

**Comment by siegy22** [comment]
Got it!

This line does the trick:

```ruby
Paperclip::Attachment.default_options[:url] = "/my_sub_folder/system/:class/:attachment/:id_partition/:style/:filename"
```

Isn't there a way to configure this easier?

**Comment by crawfoal** [comment]
I came across this issue too - the README (in the testing section) says that you should be able to just set the `:path` default option, however that leaves the url out of sync. _**I'm guessing maybe this used to work, but things have changed recently?**_

For testing, I ended up changing the `:url` instead of the `:path` and this worked:

```ruby
#config/environments/test.rb
Rails.application.configure do
  ...
  config.paperclip_defaults = {
    url: '/test_files/system/:class/:attachment/:id_partition/:style/:filename'
  }
end
```

Then in the `rails_helper.rb` (or `spec_helper.rb`), you need

```ruby
config.after(:suite) do
  FileUtils.rm_rf(Dir["#{Rails.root}/public/test_files/"])
end
```

But I wasn't able to get things working with a tmp folder in the spec directory like the README suggests you can do, I had to have that temporary `test_files` folder in the pubic directory.

@poporul It looks like you might have worked on something related to this recently (PR #2273). Do you have some input here?

@tute

**Comment by poporul** [comment]
@crawfoal you can try to pass `url` option when defining `has_attached_file`, for example https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip.rb#L122-L133, https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip.rb#L183-L195

**Comment by poporul** [comment]
@crawfoal in this PR I reduced number of arguments for `Paperclip::UrlGenerator`'s constructor, main logic remained the same.

**Comment by crawfoal** [comment]
Yea, I know, but what about the global configuration of `path` not working like it used? Should the documentation be updated? Or does something need fixed? (not saying it was that specific PR, I just tagged you because it seemed like you might be familiar with this topic)

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
