### ISSUE TITLE
Paperclip::Errors::NotIdentifiedByImageMagickError in Windows

### ISSUE THREAD

**Issue by aboutqx** [thoughtbot/paperclip#2330]
It seems that paperclip use identify as exe in windows,

`Command :: SET PATH=C:\file-5.03-bin\bin;%PATH% & identify -format '%wx%h,%[exif:orientation]' "C:/Users/AppData/Local/Temp/5415c7fe534a63366b48d388f204c32820161028-7156-f2nblm.jpg[0]" 2>NUL`.,

while only `magick identify` command  works in windows,and there in no identify.exe in windows in the latest version ImageMagic.
And only `Paperclip.options[:command_path]` is used, the `Paperclip.options[:image_magick_path]` seems ignored.

About imageMagick in windows can be found [there](http://www.imagemagick.org/script/binary-releases.php).

**Comment by aboutqx** [comment]
I've made a  [pull request](https://github.com/thoughtbot/paperclip/pull/2332),and it works with ImageMagick 7.0.3-4 Q14 x64 in windows.

**Comment by tute** [comment]
Thanks!! Closing in favor of PR.

**Comment by nengine** [comment]
I installed **ImageMagick-7.0.4-Q16** but getting the same error.

**Comment by dramirezCL** [comment]
Same issue on Windows 7, ImageMagick-7.0.5-10, ruby 2.3.3p222.
Is there a workaround for this problem in the meantime?

**Comment by DivideBySara** [comment]
Same issue on Windows 10, Rails 5.0.2, ImageMagick 7.0.6-0 Q16 x64.

**Comment by ShubhaShashikanth** [comment]
Same issue on Windows7, ImageMagick-7.0.7-21-Q16-x64-dll, ruby 2.4.3p205. Is there any workaround for this problem in the meantime?

**Comment by srsutherland** [comment]
For anyone googling this issue and arriving here: ImageMagick 7 removed all of the binaries for the individual command binaries (identify.exe, convert.exe, etc), rolling them into the magick.exe command as arguments. Since this PR hasn't been accepted at time of writing, the workaround is to **re-install ImageMagick _making sure that_ "Install legacy utilities (e.g. convert)" is checked.** This adds the expected command binaries (in this case identify.exe) allowing it to work as normal.
