### ISSUE TITLE
undefined method `image' if joins tables

### ISSUE THREAD

**Issue by deni5n** [thoughtbot/paperclip#2355]
class Photo < ApplicationRecord
  has_many   :user_comments
  has_many   :users, through: :user_comments
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

class User < ApplicationRecord
  has_many :user_comments
  has_many :photos, through: :user_comments
end

class UserComment < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

execute [union = UserComment.joins(:user,:photo).where('photos.id = ?',1).first]
OK
execute [union.image]
ERROR
NoMethodError: undefined method `image' for #<UserComment:0x007fe8845fbf58>

how fix ?

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand your issue in order to help you.

Sorry we don't have the time now to help you with this question, and thanks!
