### ISSUE TITLE
How to edit multiple files from nexted resource using paperclip??

### ISSUE THREAD

**Issue by babind** [thoughtbot/paperclip#2357]
i want to edit photos from asset model where asset has_many photos . The number of photo is greater than 1.

**Comment by tute** [comment]
Hi, @babind! I suggest that you ask about this in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better understand your task in order to help you successfully.

For now I'll close this issue, as it's not a bug in paperclip worthy of living in its issue tracker.

Thanks!
