### ISSUE TITLE
paperclip (5.1.0) - CSV file validation error

### ISSUE THREAD

**Issue by casecamp** [thoughtbot/paperclip#2418]
While uploading csv file we are getting this error

`ActiveRecord::RecordInvalid - Validation failed: Photo content type is invalid, Photo is invalid:`

In model content type, the validation I am using is `text/csv`

**Comment by casecamp** [comment]
any one got solution for this?

**Comment by wmakley** [comment]
My app is setting file_content_type to text/plain when I upload a CSV for some reason, even though the file upload object has text/csv as the MIME type. This might be the same issue.

**Comment by hoffmanilya** [comment]
+1

**Comment by siannopollo** [comment]
I am having this issue as well. I am _pretty sure_ the error stems from the fact that `#type_from_file_command` can return content types for text-based files that is dependent on some esoteric flags found in the content of the file. For example, if you have a .csv file with a line in it like this:
```
C some other content
```
that file will be identified as a Fortran file (text/x-fortran) because that is apparently how comments in Fortran work.

I ran into this a few months ago and couldn't stop to get the correct solution, but I ran into this same issue with another file type. Now I have a .csv file that is being identified as text/x-c, probably due to something similar where some C syntax is coincidentally in the CSV file and Paperclip is using the content-based detection over the type inferred by the file extension.

I'm using this monkeypatch for now so this doesn't keep breaking things:
``` ruby
Paperclip::ContentTypeDetector.class_eval do
  def detect
    if blank_name?
      SENSIBLE_DEFAULT
    elsif empty_file?
      EMPTY_TYPE
    elsif calculated_type_matches.any?
      calculated_type_matches.first
    elsif possible_types.any? {|type| type.include? 'text/'}
      possible_types.first
    else
      type_from_file_contents || SENSIBLE_DEFAULT
    end.to_s
  end
end
```
This code will use the first of the possible types (based on file extension) for any file identified as a text-based file, and will not try to guess the content type based on the content of the file.

Paperclip maintainers: Could there be any problems with this approach? As in, are there any plain text files which will be more accurately detected based on their content vs. their file extension?

**Comment by krim** [comment]
Any information about this problem?

**Comment by diproart** [comment]
ckeditor does [this](https://github.com/galetahub/ckeditor/blob/115a50628baceeac5cc37363db082e3f5ba03c76/lib/generators/ckeditor/templates/active_record/paperclip/ckeditor/attachment_file.rb#L8) for attachment

```ruby
do_not_validate_attachment_file_type :data
```

**Comment by mkonikowski** [comment]
Hello! Are there any news about this issue? I have a validation checking for `content_type: 'text/csv'` which was working on `paperclip (4.2.1)`, but stopped after upgrade to `paperclip (5.3.0)`. Files that were previously seen as CSVs, now are `text/plain`...

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.

**Comment by diproart** [comment]
> ...we will be deprecating Paperclip ...

what to use instead?
your recommendations for users?
where to read about this "news"?

**Comment by jaspertandy** [comment]
@diproart they've updated the README, in case you haven't already found this: https://github.com/thoughtbot/paperclip#deprecated

**Comment by cengiz7** [comment]
Try `"text/comma-separated-values"` for the csv file validations.
