### ISSUE TITLE
Post processing callbacks are run on invalid attachments.

### ISSUE THREAD

**Issue by jhawthorn** [thoughtbot/paperclip#2462]
From the README

>  NOTE: Post-processing will not even start if the attachment is not valid according to the validations. Your callbacks and processors will only be called with valid attachments.

However in [attachment.rb](https://github.com/thoughtbot/paperclip/blob/82cd3781b4bbfe20778fe5f9a6802d348cd5ee1a/lib/paperclip/attachment.rb#L509-L515)

```
instance.run_paperclip_callbacks(:post_process) do
  instance.run_paperclip_callbacks(:"#{name}_post_process") do
    if !@options[:check_validity_before_processing] || !instance.errors.any?
      post_process_styles(*style_args)
    end
  end
end
```

The check for validity happens inside the `run_paperclip_callbacks` blocks, so the callbacks are always run.

Reported by @karlentwistle  in solidusio/solidus#2064

**Comment by karlentwistle** [comment]
I had a go at fixing this as you can see 🙈 I can only get the issue to bubble if I call `instance.valid?` which does actually return false and would circumvent the post processes for the invalid attachment but this breaks *a lot* of tests if called here https://github.com/karlentwistle/paperclip/commit/f1fa56b5d1206d80da4fcfc0ffb3bcf468517e7a instead of `instance.errors.any?`.

**Comment by sidraval** [comment]
Looks like there's an open PR that will be merged, closing.

**Comment by ssinghi** [comment]
This has been fixed at https://github.com/kreeti/paperclip/commits/master.
