### ISSUE TITLE
Is this gem still being maintained?

### ISSUE THREAD

**Issue by smoyth** [thoughtbot/paperclip#2477]
Seems there has been very little activity.

I also submitted a [PR](https://github.com/thoughtbot/paperclip/pull/2350) months ago with a major functionality addition and didn't get a single response from the maintainers.

I realize open source is hard, just wanting to know the status so we can make informed decisions.

Thanks for all the great work!

**Comment by blairanderson** [comment]
Hi there 👋 

Paperclip is the most popular and mature file upload/process library in the ruby ecosystem and probably won't have features of that size/scope accepted. 

You should look into creating a plugin/processor instead.

**Comment by hooverlunch** [comment]
Perhaps but I'm still curious why nobody would tell me that in the PR. And also as I said there have not been hardly any commits to this gem in a while. So I'm just curious what the status is.

**Comment by jeremywadsack** [comment]
Was just thinking the same thing. The only updates since December were an update to the Thoughtbot logo and the copyright year (which seems to only be relevant because they changed the copyright).

There are a large number of open PR and I don't see much activity on them except by hound-ci. Many of these are fixing bugs with upstream gems and ensuring support for Rails 5.1.

**Comment by Daniel-ltw** [comment]
I reckon open source and easy to code is really becoming a huge problem with the ruby eco system. 

Everyone with a new feature/idea starts forking and do their own little thing and never come back with it. Everyone else is also left behind with what is happening within the community. There is no one place or a single source of truth. 

I was thinking of the fact that paperclip being the most matured gem will evolve and grow, with additional maintainers added occasionally to help maintain the state of the gem, allow it to not fall behind. This is starting to look like a huge problem going back to my first sentence. People could just come up with new stuff to replace this and move on. 

So it comes down to either, maintainers of paperclip start adding more maintainers to help keep this alive or everyone start diverging and start their own alternative and make the whole ruby eco system even more massive than before. 

P.S.: Just me ranting. If people from Thoughtbot think this comment is in-appropriate, then do remove it.

**Comment by janko-m** [comment]
> I reckon open source and easy to code is really becoming a huge problem with the ruby eco system.

Why is open source becoming a problem in the Ruby ecosystem? I think it's amazing that people have built so many great libraries over the years that are free and open.

> Everyone with a new feature/idea starts forking and do their own little thing and never come back with it. Everyone else is also left behind with what is happening within the community. There is no one place or a single source of truth.

Can you give me some examples? I see many large open pull requests, for example one that adds [background processing](https://github.com/thoughtbot/paperclip/pull/2261). I don't think that forking and not contributing back is the problem, it's more that maintainers of Paperclip don't have time at the moment.

> I was thinking of the fact that paperclip being the most matured gem will evolve and grow, with additional maintainers added occasionally to help maintain the state of the gem, allow it to not fall behind.

Why do you think that Paperclip is the most mature gem? Paperclip is among the first Ruby file upload libraries that gained popularity, but that just means that it has been around the longest, it doesn't mean that it necessarily made the best design decisions which would allow it to evolve further.

> So it comes down to either, maintainers of paperclip start adding more maintainers to help keep this alive or everyone start diverging and start their own alternative and make the whole ruby eco system even more massive than before.

These are definitely not the only two options; a third option is that Ruby developers transition to any of the other existing file upload libraries, like CarrierWave, Dragonfly, Refile, or Shrine.

I'm one of the Ruby developers that is maintaining a new solution for some time now, called [Shrine](https://github.com/janko-m/shrine), which was inspired by [Refile](https://github.com/refile/refile), where I was a core maintainer before.

Primary reason for not contributing to Paperclip was that I simply couldn't use it in the current form, because I don't use Rails or ActiveRecord or ActiveSupport or ActiveJob. So I could choose to either spent insane amount of time decoupling Paperclip from Rails (and I'm not even sure that would be a welcome change), or join/build another solution that is decoupled from the start.

Second reason was that Paperclip's storage abstraction is leaky, I had a hard time implementing [paperclip-dropbox](https://github.com/janko-m/paperclip-dropbox). For example, compare [`Paperclip::Storage::S3`](https://github.com/thoughtbot/paperclip/blob/82cd3781b4bbfe20778fe5f9a6802d348cd5ee1a/lib/paperclip/storage/s3.rb) and [`Shrine::Storage::S3`](https://github.com/janko-m/shrine/blob/edc627a87923d8d38842c480bca6805339be936f/lib/shrine/storage/s3.rb).

The third reason was that I didn't find Paperclip well designed. `Paperclip::Attachment` has way too many responsibilities: uploading files, syncing with the model instance, representing uploaded files etc. In Shrine these are split into `Shrine`, `Shrine::Attacher`, and `Shrine::UploadedFile` classes. Paperclip is also somewhat coupled to ImageMagick, which is just one processing tool. Finally, the MIME type spoof detection didn't prove to be reliable, e.g. it can reject valid files.

There are so many things that aren't ideal with Paperclip, especially if you compare it with other file upload libraries, so a lack of maintenance shouldn't be considered a terrible loss, because there are great replacements.

**Comment by jyurek** [comment]
There has been very little activity. To be perfectly honest, we write software that we use, and Paperclip has either been sufficient for our purposes or not relevant for our work, and so it's fallen off the radar. And, as @janko-m said, much of it isn't ideal. It was written quite some time ago. It filled the needs of its time, and it grew beyond what became maintainable. This is completely on me as its creator and primary maintainer for years. I don't like it, but there it is.

So, to that end, what can we do? One thing would be to flat out close it; I'm not thrilled with this as people still use it. Another would be to rewrite something better; others have done this already so where's the point in that? A third would be to spend the time renovating it until it's in a place we want it; I like the idea of doing this, but as I said above, we simply don't use it as much anymore and we'd need to spend a lot of time on said renovations. Finally, we can open up direct maintenance to others instead of having to deal in PRs that may or may not get attention.

**Comment by jeremywadsack** [comment]
@jyurek Thank you for following up on this.

> Finally, we can open up direct maintenance to others instead of having to deal in PRs that may or may not get attention.

I think that's the clearest solution. If other people are using this, who have the skill and time to maintain it, you should accept their help. :)

**Comment by Daniel-ltw** [comment]
agreed to the above as well, that would be ideal.

**Comment by wyaeld** [comment]
@jyurek There is an understandable expectation that a gem that has been around so long, associated with an organisation like thoughtbot is being well-maintained.

If that is not the case, it should be spelt out clearly, to encourage people to at least consider other projects like https://github.com/janko-m/shrine by @janko-m which do have active support and interest.

No-one needs to be shackled to a project forever if they have moved on, but an open call for more maintainers will soon indicate if people have sufficient investment to take some of the work off your shoulders.

**Comment by Daniel-ltw** [comment]
I guess with that "understandable expectation", many gem have adopted paperclip as their go to gem for file upload solution. This has become an issue that has surfaced. 

Ruby is such a great language that it enables developer to create what they need in a way that they can express themselves. People might just assume things and not do sufficient research into a gem before adopting them as dependencies, following more general examples out in the open. This would later bite them and others who use that gem. 

I also suggest that places like awesome-ruby should be updated with such information, so others could make more informed decisions when picking gems/dependencies.

**Comment by sidraval** [comment]
We're deprecating paperclip. We regret not being clearer about this over the last few months / year.

**Comment by radar** [comment]
@sidraval I think it would be good to put a notice saying that in the README.
