### ISSUE TITLE
Image not saving OpenURI::HTTPError: 404 Not Found

### ISSUE THREAD

**Issue by waclock** [thoughtbot/paperclip#2508]
When I try saving an image from a certain website (URL) I get the error

`OpenURI::HTTPError: 404 Not Found`

The URL is http://www.dbsbeautystore.cl/tienda/image/cache/data/productos/nuevos%20abril%202015/121-500x500.png

I don't know how to proceed and save the image

By the way what I do in terms of code is equivalent to

```
@product.image = "http://www.dbsbeautystore.cl/tienda/image/cache/data/productos/nuevos%20abril%202015/121-500x500.png"

@product.save
```

**Comment by klaudia21** [comment]
Hi!

This is probably caused by [this line](https://github.com/thoughtbot/paperclip/blob/7edb35a2a9a80c9598dfde235c7e593c023fc914/lib/paperclip/io_adapters/http_url_proxy_adapter.rb#L7). Your URL is already encoded so this line transforms your URL to
```
[1] pry(main)> URI.escape("http://www.dbsbeautystore.cl/tienda/image/cache/data/productos/nuevos%20abril%202015/121-500x500.png")
=> "http://www.dbsbeautystore.cl/tienda/image/cache/data/productos/nuevos%2520abril%25202015/121-500x500.png"
```
It encodes `%` to `%25` and creates different URL. If you provide not encoded URL it might work.

**Comment by waclock** [comment]
You're absolutely right, great eye
