### ISSUE TITLE
Is it possible to disable URI obfuscation?

### ISSUE THREAD

**Issue by fltiago** [thoughtbot/paperclip#2515]
I don't know if this right place to ask this question. Let me know if I'm doing something wrong.

So, I'm using paperclip with s3 integration and is working properly, but now a mobile application is trying to access the images directly from s3, as paperclip uses obfuscation isn't possible to infer the URL using only the data that are saved on the db (as far as I know).

So I want to know if it's possible to disable obfuscation for now and reprocess all images to save in inferable way.

PS: I know that probably the best approach is to build a API to access the images, but I don't want to do that right now.

**Comment by mike-burns** [comment]
Yes: change the `url` option in `has_attached_file` to not have `:hash` in it.

**Comment by adolfopeccin** [comment]
Sorry to revive the issue, but we are renaming a model that uses URI Obfuscation and we are having some problems with file names generated with hash.

The model used `:path => ":class/:id/:style/:hash.:extension"``
Database saved the original file name (ex. file_name.ogg)
The file saved into S3 is the hash.extension.

Now we can't directly disable hash and if we rename the model, all files break because generated files names in S3 using the `:hash.:extension`

Any idea how to resolve this?
