### ISSUE TITLE
/tmp directory filling up with RackMultipart* files

### ISSUE THREAD

**Issue by rfc2822** [thoughtbot/paperclip#413]
It seems that the uploaded RackMultipart\* files in /tmp are not deleted by Paperclip after being used, resulting in a filling up /tmp directory until the quota is reached and then it fails. See also http://groups.google.com/group/paperclip-plugin/browse_thread/thread/a797859dc6972b1f

**Comment by diegodurante** [comment]
Is this issue still open? Any updates?

I am having this issue, because Paperclip is creating a lot of .bak files in /tmp folder that are rarely deleted as my instances are rarely restarted.

I know that I can fix this with a cron job but my question is if this should be managed by paperclip or not. What do you think guys?

I am using:
- ruby 2.1.8
- rails 4.2.6
- paperclip '~> 5.1'
- paperclip-compression '~> 0.3.16'
- paperclip-av-transcoder '~> 0.6.4'

This is what I have in my /tmp folder:

> /tmp$ ls -alt
**total 3348**
drwxrwxrwt  2 root   root      53248 Apr  4 11:25 .
-rw-------  1 deploy www-data      0 Apr  4 10:46 ce9729bb96f76f67e8457070a352792c20170404-31709-eor1m8.png.bak
-rw-------  1 deploy root          0 Apr  3 18:07 754ac924b08ab3f6fe3730582f8b124620170403-22282-biufaa.png.bak
-rw-------  1 deploy root          0 Apr  3 18:07 e9a2ba94a021551ae5b90178f7b88af920170403-22282-7f1u9i.png.bak
-rw-------  1 deploy root          0 Apr  3 18:06 3f0d0aef49a24e4b7440b56c305547a920170403-22282-17xg4um.png.bak
-rw-------  1 deploy root          0 Apr  3 18:06 ba1931a27da94a97851693b2a3cecb6020170403-22282-1pvqcjo.png.bak
-rw-------  1 deploy root          0 Apr  3 18:06 9848e3ecc1a9c2a4b6145bc498e1a5e320170403-22282-d328qd.png.bak
-rw-------  1 deploy root          0 Apr  3 18:06 d97cc1c926ca72357bcdc98d71b9312320170403-22282-j3630i.png.bak
-rw-------  1 deploy root          0 Apr  3 18:06 edba69972a9db2f8e8c8f870b3c0d7ae20170403-22282-1s7uh0j.png.bak
-rw-------  1 deploy root          0 Apr  3 18:05 17a0675229a40ee303b1ec0bbefbffb420170403-22282-1t8vcfo.png.bak
-rw-------  1 deploy root          0 Apr  3 18:05 cfe3f443ac08a49be706f61e23cc66c520170403-22282-ws9d8e.png.bak
.................................
-rw-------  1 deploy root          0 Dec 15 23:57 f0b6771bb45ab2ddb8be382a6ab5fd3e20161215-10301-14fufh9.png.bak
-rw-------  1 deploy www-data      0 Dec 15 23:47 7d09134931e1929798cd45ea35dc619d20161215-10260-us0umr.png.bak
-rw-------  1 deploy www-data      0 Dec 15 14:24 8aad699dc49b4cd7df1898c314f1bbd320161215-3399-1glmfwl.png.bak
-rw-------  1 deploy www-data      0 Dec 15 14:22 b09af108ea61916914afad4fb08551ed20161215-3388-16kbzvc.png.bak
drwxr-xr-x 23 root   root       4096 Dec 15 09:23 ..
