### ISSUE TITLE
Randomize the file name

### ISSUE THREAD

**Issue by sebfie** [thoughtbot/paperclip#615]
Hello,

I want to randomize the filename of each file uploaded with paperclip, how can i configure that? I found how to do that for each file attachment but i will prefer to configure paperclip to do that on each file upload.

Thank you!

**Comment by NeoElit** [comment]
Apologies for posting in this old thread. It's more kind of a query.

I want to randomize filename with something similar to an access_token function in the latest version. However, I don't want one more field on the table. Instead i want to use the filename itself as the token since using an interpolator will leave the `[attachtment]_file_name` irrelevant.

I would like to know which would be the best callback to re-assign the `[attachtment]_file_name` to a random value and also any pitfalls that I'm blind on. Currently I'm leaning on `before_post_process`

**Comment by NeoElit** [comment]
`before_post_process` was a bad idea. It ended up creating duplicate files for the original. Guess the best shot as of now is an additional column :(

**Comment by NeoElit** [comment]
That was a bit idiotic. I could easily randomize the original_filename before it reaching paperclip.. Seems better for cases when urls should be guessable based on styles but not across attachments
