### ISSUE TITLE
Calling Model#save can raise AWS::S3::Errors::RequestTimeout

### ISSUE THREAD

**Issue by indirect** [thoughtbot/paperclip#751]
Hi guys, I've been noticing that after switching to `aws-sdk`, calling #save on a model with a paperclip attachment will now sometimes (I assume only those times when S3 times out) raise an `AWS::S3::Errors::RequestTimeout` error. It seems completely crazy to me to have to add a `rescue AWS::S3::Errors::RequestTimeout` clause after every single time that I ever call save anywhere in my app. Shouldn't paperclip just catch the error and either retry or report that the save failed? Thanks.

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by brettv** [comment]
it is no longer an issue for me, thanks!

**Comment by jasonfb** [comment]
I remember this issue from so long ago. I never quite identified it but I haven't seen it an awhile. (We are on AWS-SDK 1.27.0)

Some of the people here may be reporting this issue when the file is read by another process before Paperclip processes the styles. In those cases, the fix is to reset the read head of the file using the rewind method on Ruby's File I/O object (http://ruby-doc.org/core-2.0.0/IO.html#method-i-rewind)

But I do think that not all cases of the symptom involve that, only some of them.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by medBouzid** [comment]
@maclover7  I have actually this issue 
I am using 

    gem 'paperclip', '~> 4.3.0'
    gem 'aws-sdk', '< 2.0'

**Comment by murilosardinha** [comment]
I have the save error. It seems to need another downgrade. Any help?
```
gem 'paperclip', '4.1.1'
gem 'aws-sdk',    '1.38.0'
```

**Comment by medBouzid** [comment]
@murilosardinha I found that the problem is because  **the difference between the request time and the current time is too large** so verify if your machine time (especially date) is correct.

PS : for every one who use Amazon S3 be sure to backup your content somewhere else than amazon (they could close your account at any time without any reason and then if you try to contact them they never respond)
