### ISSUE TITLE
When uploading I'm getting IOError (closed stream)

### ISSUE THREAD

**Issue by brutuscat** [thoughtbot/paperclip#875]
Hi, having this issue when trying to upload a file using Rails Admin and using:

ruby 1.9.3p194
Rails 3.2.3 with `config.threadsafe!`
Paperclip from thoughtbot/paperclip@22a2a85d117e
zbatery rack server behind nginx

```
Command :: identify -format %wx%h '/home/entretenerse/releases/20120514105703/tmp/stream20120516-29771-1smz520.jpg[0]' 2>/dev/null
Completed 500 Internal Server Error in 1384ms

IOError (closed stream):
  activesupport (3.2.3) lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'
  activesupport (3.2.3) lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'
  cocaine (0.2.1) lib/cocaine/command_line.rb:30:in `block in run'
  cocaine (0.2.1) lib/cocaine/command_line.rb:51:in `with_modified_path'
  cocaine (0.2.1) lib/cocaine/command_line.rb:28:in `run'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip.rb:103:in `run'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip/geometry.rb:22:in `from_file'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip/thumbnail.rb:35:in `initialize'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip/processor.rb:33:in `new'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip/processor.rb:33:in `make'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip/attachment.rb:441:in `block in post_process_style'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip/attachment.rb:440:in `each'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip/attachment.rb:440:in `inject'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip/attachment.rb:440:in `post_process_style'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip/attachment.rb:433:in `block in post_process_styles'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip/attachment.rb:432:in `each'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip/attachment.rb:432:in `post_process_styles'
  /home/entretenerse/shared/bundle/ruby/1.9.1/bundler/gems/paperclip-22a2a85d117e/lib/paperclip/attachment.rb:425:in `block (2 levels) in post_process'
```

Right now this is killing me.... 

Upgrade Paperclip would fix this? Any notes about upgrading from 2.something to version3?

**Comment by braindeaf** [comment]
So the solution for this is to ensure that if you have custom processor that it always returns a new file? I have processors that read from the original file just to extract meta data but don't alter the file in any way. It seems a little pointless to generate a new file in this instance. I assume I'd have to do the same as above, even if it's a 5Gb video file for example.

**Comment by Jakenberg** [comment]
I am on paperclip `v5.1.0` and still see this error. However, I believe I can shed some light on why it happens... 

1. In my case, I found that I would only see the IO stream closed stacktrace when using a custom processor (e.g. `has_attached_file :attachment, processors: [:transcoder]`). If I removed the processor definition I would no longer see the error. I believe that is because...

2. When trying to process a kind of file that is unknown to the processor, it seems to simply close the stream. For example, if I try to upload a video file for an attachment that is intended to be an image, I saw the closed stream stacktrace.

3. If the AR model calls `do_not_validate_attachment_file_type :attachment` then there is no fail safe for invalid file types, which allows # 2 to happen. If this method call is removed in place of the proper validations (`validates_attachment :attachment, content_type: %w(video/mp4 video/mpeg video/quicktime) }`), I see the expected `422` error instead of the IO stream closed stacktrace.

This ended up being a sufficient solution in my case; my tests are passing :) Hopefully this helps someone save some hair!

**Comment by mahemoff** [comment]
I had two custom processors and with the first one in the chain, where both (under some conditions were simply passing through the file. It was fine to just return `file` (ie the argument passed to the processor's constructor). But the second one gave this `closed stream` error, so perhaps it only applies to the last processor in the chain.

Also - I was able to work around this by returning `File.open(File.expand_path(@file.path))`, so it seems there's no need to copy/rewrite the file. (Probably just File.open(@file.path)` works too.)

**Comment by Gargron** [comment]
I'm wondering if `File.open(File.expand_path(@file.path))` must be done every time a processor is returning a file untouched (e.g. "nothing to do here"), or only on the first processor in the chain? Likewise, I believe paperclip's own code uses the `rb` flags, I wonder if those also need to be included in the call.

Also, this wouldn't affect the amount of temp files that Paperclip generates, right? Does it mess with Paperclip's ability to clean up after itself?

**Comment by joshuapinter** [comment]
For anybody that lands here with a similar error. I was getting this error when it was trying to process a `.dat` file, which it thought was a video file. Not a clear error message, but once I treated it as a normal file and did not try to convert it, the error disappeared.

**Comment by hedgesky** [comment]
I also had this issue and was able to fix it by `File.open(file.path).tap(&:binmode)`. Using `binmode` is probably not required, but decided to be on the safe side and do what [paperclip does](https://github.com/thoughtbot/paperclip/blob/v6.1.0/lib/paperclip/tempfile_factory.rb#L7).

As far as my investigation showed, the issue lies in following line: https://github.com/thoughtbot/paperclip/blob/v4.3/lib/paperclip/attachment.rb#L529. There, paperclip creates an adapter (for example, `Paperclip::FileAdapter`) to a resulting output File object and closes latter afterwards. However, if output file was already an adapter, new adapter isn't created but existing one got closed anyway. And therefore a closed stream is passed further, which isn't expected by other parts of the library, resulting in `IOError (closed stream)` in some setups. Notably, it happens with S3 storage strategy and does not with local file storage, making it harder to investigate.

This issue reveals itself when a custom processor does nothing and just returns provided `file` without creating new instances of `File` or `Tempfile`. At that moment, `file` is an adapter provided by paperclip, which leads to an issue described above. By seemingly just "reopening" existing file in reality we return a `File` instead of `Paperclip::FileAdapter`, which causes issue to gone.
